"""C++ 赛道。"""

TRACK: dict = {
    "key": "cpp",
    "system_prompt_extra": """你是资深 C++ 技术面试辅助 AI。用户正在进行 C++ 技术面试，问题涉及
C++ 语言特性（RAII/智能指针/移动语义/模板元编程/constexpr/concepts/协程）、
内存管理（new/delete/placement new/内存池/智能指针/RAII）、
STL（容器/算法/迭代器/allocator）、C++11/14/17/20/23 新特性、
并发编程（std::thread/mutex/atomic/future/promise/async）、
操作系统（进程/线程/内存管理/文件系统/网络编程）、
编译与链接（预处理器/编译器优化/链接器/动态库/静态库/CMake）、
设计模式（C++ 实现）、网络编程（socket/epoll/iocp/Boost.Asio）、
图形学（OpenGL/Vulkan/DirectX/着色器/渲染管线）、
游戏引擎（Unreal Engine/Unity/ECS/物理引擎）、
音视频（FFmpeg/编解码/流媒体/WebRTC）、
嵌入式（RTOS/交叉编译/驱动开发/内存映射/中断）、
数据库（SQLite/MySQL connector/嵌入式数据库）、
性能优化（缓存友好/分支预测/SIMD/内存对齐/Profile）、
测试（Google Test/Catch2/doctest/Valgrind/AddressSanitizer）
等 C++ 技术栈。

回答应围绕 C++ 生态，用 C++ 开发者熟悉的术语和场景。""",

    "resume_intro_extra": """侧重 C++ 技术栈经验：突出 C++ 语言深度理解（C++11~23 新特性）、
系统编程/底层开发经验、图形学/游戏引擎开发能力、性能优化与调优实践、
嵌入式/IoT 开发经验、多线程并发编程能力、跨平台开发经验。""",

    "terms": {
        # ── C++ 语言特性 ──
        "RAII": ["raii", "r a i i", "r a i i", "resource acquisition", "瑞爱", "r a 2 i"],
        "智能指针": ["智能指针", "智能指真", "smart pointer", "斯马特pointer"],
        "unique_ptr": ["uniqueptr", "unique ptr", "unique pointer", "尤尼柯pointer", "unique pointer", "独占指针"],
        "shared_ptr": ["sharedptr", "shared ptr", "shared pointer", "谢尔德pointer", "shared pointer", "共享指针"],
        "weak_ptr": ["weakptr", "weak ptr", "weak pointer", "威克pointer", "weak pointer", "弱指针"],
        "移动语义": ["移动语义", "move semantics", "move semantics", "mu夫semantics"],
        "右值引用": ["右值引用", "rvalue reference", "r value reference", "右直引用"],
        "左值引用": ["左值引用", "lvalue reference", "l value reference"],
        "完美转发": ["完美转发", "perfect forwarding", "perfect forward", "完美for ward"],
        "std::move": ["stdmove", "std move", "s t d move", "s t d move"],
        "std::forward": ["stdforward", "std forward", "s t d forward"],
        "拷贝构造": ["拷贝构造", "copy constructor", "copy constructor", "考皮康思抓克特"],
        "移动构造": ["移动构造", "move constructor", "move constructor"],
        "拷贝赋值": ["拷贝赋值", "copy assignment", "copy assignment"],
        "移动赋值": ["移动赋值", "move assignment", "move assignment"],
        "三五法则": ["三五法则", "rule of three five", "rule of 5", "三五原则", "三/五法则"],
        "零法则": ["零法则", "rule of zero", "rule of 0"],
        "模板元编程": ["模板元编程", "template metaprogramming", "坦普雷特元编程", "TMP", "tmp", "模板元"],
        "SFINAE": ["sfinae", "s f i n a e", "sfinae", "s f i n a e", "sfinae"],
        "Concepts": ["concepts", "con cepts", "concepts", "concept", "概念"],
        "requires": ["requires", "re quires", "requires", "required", "瑞快尔"],
        "constexpr": ["constexpr", "const expr", "const expression", "const expression", "康斯特expression"],
        "consteval": ["consteval", "const eval", "const eval"],
        "constinit": ["constinit", "const init", "const init"],
        "协程": ["协程", "coroutine", "科入体", "co routine", "c++20协程"],
        "co_await": ["coawait", "co await", "co await", "co wait"],
        "co_yield": ["coyield", "co yield", "co yield", "co yield"],
        "co_return": ["coreturn", "co return", "co return"],
        "Modules": ["modules", "mo dules", "modules", "c++20模块", "模组"],
        "三路比较": ["三路比较", "three way comparison", "spaceship operator", "太空船运算符", "<=>"],
        "std::variant": ["stdvariant", "std variant", "s t d variant", "variant"],
        "std::optional": ["stdoptional", "std optional", "s t d optional", "optional"],
        "std::any": ["stdany", "std any", "s t d any", "any"],
        "std::span": ["stdspan", "std span", "s t d span", "span"],
        "std::string_view": ["stdstringview", "std string view", "s t d string view", "string view", "斯追view"],
        "Lambda": ["lambda", "l a m b d a", "兰布达", "拉姆达", "lambda表达式"],
        "Ranges": ["ranges", "ran ges", "ranges", "c++20 ranges", "润哲"],

        # ── 内存管理 ──
        "new/delete": ["new delete", "new", "delete", "new delete", "牛delete"],
        "placement new": ["placementnew", "placement new", "placement new"],
        "内存池": ["内存池", "memory pool", "memory pool", "麦莫瑞铺", "内存铺"],
        "对象池": ["对象池", "object pool", "object pool", "奥布杰克特铺"],
        "malloc": ["malloc", "mal loc", "马洛克", "malloc", "c malloc"],
        "free": ["free", "f r e e", "福利", "free", "c free"],
        "calloc": ["calloc", "cal loc", "卡洛克", "calloc"],
        "realloc": ["realloc", "re alloc", "瑞阿洛克", "realloc"],
        "内存泄漏": ["内存泄漏", "内存泄露", "内层泻露", "memory leak", "麦莫瑞leak"],
        "野指针": ["野指针", "dangling pointer", "当令pointer", "dangling"],
        "悬空指针": ["悬空指针", "悬空指真", "dangling pointer"],
        "双重释放": ["双重释放", "double free", "double free"],
        "缓冲区溢出": ["缓冲区溢出", "buffer overflow", "buffer overflow", "buffer overflow"],
        "栈溢出": ["栈溢出", "stack overflow", "stack overflow", "站溢出"],
        "堆碎片": ["堆碎片", "heap fragmentation", "heap fragment", "内存碎片"],
        "内存对齐": ["内存对齐", "memory alignment", "alignof", "a line of", "align as"],
        "Allocator": ["allocator", "al lo cator", "阿楼k特", "allocator", "分配器"],
        "std::pmr": ["stdpmr", "std pmr", "s t d pmr", "pmr"],
        "Sanitizer": ["sanitizer", "sa ni tizer", "sanitizer", "sanitize", "消毒器"],
        "AddressSanitizer": ["addresssanitizer", "address sanitizer", "asan", "a s a n"],
        "Valgrind": ["valgrind", "val grind", "瓦欧grind", "valgrind"],

        # ── STL ──
        "vector": ["vector", "v e c t o r", "维克特", "vector", "向量", "容器"],
        "list": ["list", "l i s t", "李斯特", "list"],
        "deque": ["deque", "d e q u e", "迪Q", "deque", "deque", "双端队列"],
        "map": ["map", "m a p", "迈普", "map", "map"],
        "set": ["set", "s e t", "赛特", "set", "set"],
        "unordered_map": ["unorderedmap", "unordered map", "unordered map", "哈希map", "哈西map"],
        "unordered_set": ["unorderedset", "unordered set", "无序set"],
        "priority_queue": ["priorityqueue", "priority queue", "priority queue", "优先队列"],
        "stack": ["stack", "s t a c k", "斯达克", "stack"],
        "queue": ["queue", "q u e u e", "Q", "queue"],
        "array": ["array", "a r r a y", "阿瑞", "array", "array"],
        "forward_list": ["forwardlist", "forward list", "forward list", "前向list"],
        "multimap": ["multimap", "multi map", "multi map"],
        "multiset": ["multiset", "multi set", "multi set"],
        "pair": ["pair", "p a i r", "派尔", "pair", "pair"],
        "tuple": ["tuple", "t u p l e", "太普欧", "tuple"],
        "iterator": ["iterator", "it er ator", "伊特瑞特", "迭代器"],
        "reverse_iterator": ["reverseiterator", "reverse iterator", "反向迭代器"],
        "算法": ["算法", "algorithm", "algorithm", "阿欧格瑞怎", "algorithm", "算法库"],
        "sort": ["sort", "s o r t", "sort", "sort", "排序"],
        "find": ["find", "f i n d", "放的", "find", "查找"],
        "find_if": ["findif", "find if", "find if", "条件查找"],
        "transform": ["transform", "trans form", "川斯form", "transform"],
        "accumulate": ["accumulate", "ac cu mu late", "阿Q谬雷特", "accumulate"],
        "lower_bound": ["lowerbound", "lower bound", "lower bound"],
        "upper_bound": ["upperbound", "upper bound", "upper bound"],
        "binary_search": ["binarysearch", "binary search", "binary search", "二分查找"],
        "partition": ["partition", "par ti tion", "帕提神", "partition", "分区"],
        "nth_element": ["nthelement", "nth element", "nth element"],
        "partial_sort": ["partialsort", "partial sort", "partial sort"],

        # ── 并发 ──
        "std::thread": ["stdthread", "std thread", "s t d thread", "thread"],
        "join": ["join", "j o i n", "join", "join", "join"],
        "detach": ["detach", "de tach", "迪它吃", "detach", "detach"],
        "mutex": ["mutex", "m u t e x", "缪泰克斯", "mutex", "mutex", "互斥量"],
        "lock_guard": ["lockguard", "lock guard", "lock guard"],
        "unique_lock": ["uniquelock", "unique lock", "unique lock"],
        "shared_lock": ["sharedlock", "shared lock", "shared lock"],
        "scoped_lock": ["scopedlock", "scoped lock", "scoped lock"],
        "condition_variable": ["conditionvariable", "condition variable", "条件变量", "康迪神variable"],
        "atomic": ["atomic", "a t o m i c", "阿涛mic", "atomic", "atomic"],
        "memory_order": ["memoryorder", "memory order", "memory order", "内存序"],
        "future": ["future", "f u t u r e", "飞优切", "future", "future"],
        "promise": ["promise", "pro mise", "普若米斯", "promise"],
        "packaged_task": ["packagedtask", "packaged task", "packaged task"],
        "async": ["async", "a s y n c", "阿信科", "async"],
        "thread_pool": ["threadpool", "thread pool", "thread pool", "斯瑞的铺"],
        "jthread": ["jthread", "j thread", "jthread", "joinable thread"],
        "stop_token": ["stoptoken", "stop token", "stop token"],
        "latch": ["latch", "l a t c h", "latch", "latch"],
        "barrier": ["barrier", "bar rier", "巴黎儿", "barrier", "barrier"],
        "semaphore": ["semaphore", "s e m a p h o r e", "赛马佛", "semaphore"],
        "lock-free": ["lockfree", "lock free", "lock free", "无锁"],
        "wait-free": ["waitfree", "wait free", "wait free", "无等待"],
        "CAS": ["cas", "c a s", "compare and swap", "c a s", "卡斯"],
        "ABA问题": ["aba问题", "aba problem", "a b a问题"],
        "RCU": ["rcu", "r c u", "read copy update", "rcu"],
        "spinlock": ["spinlock", "spin lock", "spin lock", "自旋锁"],

        # ── 编译 / 构建 ──
        "CMake": ["cmake", "c make", "c make", "c make", "cmake"],
        "Makefile": ["makefile", "make file", "make file"],
        "Ninja": ["ninja", "n i n j a", "宁扎", "ninja"],
        "Bazel": ["bazel", "b a z e l", "贝泽欧", "bazel"],
        "GCC": ["gcc", "g c c", "gcc", "g c c", "g加加"],
        "Clang": ["clang", "c lang", "c lang", "clang", "c lang"],
        "LLVM": ["llvm", "l l v m", "l l v m", "l l v m"],
        "MSVC": ["msvc", "m s v c", "msvc", "m s v c", "微软编译器"],
        "预处理": ["预处理", "preprocessor", "preprocessor", "普瑞processor"],
        "宏": ["宏", "macro", "macro", "macro", "迈克肉"],
        "inline": ["inline", "in line", "in line", "内联"],
        "constexpr": ["constexpr", "const expr", "const expression"],
        "链接": ["链接", "link", "link", "link", "link"],
        "静态库": ["静态库", "static library", "static lib", ".a", ".lib"],
        "动态库": ["动态库", "dynamic library", "dynamic lib", ".so", ".dll", "dll", "so文件"],
        "符号": ["符号", "symbol", "symbol", "symbol", "symbol", "森波"],
        "符号表": ["符号表", "symbol table", "symbol table"],
        "strip": ["strip", "s t r i p", "strip", "strip"],
        "PIC": ["pic", "p i c", "position independent code", "p i c"],
        "PIE": ["pie", "p i e", "position independent executable", "p i e"],
        "ODR": ["odr", "o d r", "one definition rule", "o d r", "单一定义规则"],

        # ── 操作系统 / 系统编程 ──
        "进程": ["进程", "process", "process", "普若赛斯", "进城"],
        "线程": ["线程", "thread", "斯瑞的", "线城"],
        "协程": ["协程", "coroutine", "科入体", "携程"],
        "上下文切换": ["上下文切换", "context switch", "context switch", "康泰克斯switch"],
        "虚拟内存": ["虚拟内存", "virtual memory", "virtual memory", "问道memory"],
        "页表": ["页表", "page table", "page table", "页table"],
        "TLB": ["tlb", "t l b", "translation lookaside buffer", "t l b"],
        "缺页": ["缺页", "page fault", "page fault", "缺页中断"],
        "mmap": ["mmap", "m map", "memory map", "mmap", "em map"],
        "管道": ["管道", "pipe", "pipe", "pipe", "派普"],
        "共享内存": ["共享内存", "shared memory", "shared memory", "谢尔德memory"],
        "消息队列": ["消息队列", "message queue", "message queue", "消息队猎"],
        "信号量": ["信号量", "semaphore", "赛马佛"],
        "Socket": ["socket", "s o c k e t", "骚克特", "socket", "socket"],
        "epoll": ["epoll", "e p o l l", "i poll", "epoll"],
        "IO多路复用": ["io多路复用", "io multiplexing", "i o multiplexing", "IO复用"],
        "select": ["select", "se lect", "select", "select"],
        "poll": ["poll", "p o l l", "poll", "poll"],
        "IOCP": ["iocp", "i o c p", "iocp", "io completion port"],
        "信号": ["信号", "signal", "signal", "signal", "西格no"],
        "中断": ["中断", "interrupt", "interrupt", "因特rupt", "中断"],

        # ── 网络编程 ──
        "Boost.Asio": ["boostasio", "boost asio", "boost asio", "布斯特asio"],
        "TCP": ["tcp", "t c p", "tcp", "t c p", "传输控制"],
        "UDP": ["udp", "u d p", "udp", "u d p", "用户数据报"],
        "HTTP": ["http", "h t t p", "http", "h t t p"],
        "WebSocket": ["websocket", "web socket", "web socket", "微博socket"],
        "libcurl": ["libcurl", "lib curl", "lib curl"],
        "TCP三次握手": ["tcp三次握手", "tcp three way handshake", "三次握手"],
        "TCP四次挥手": ["tcp四次挥手", "tcp four way", "四ci挥手"],
        "滑动窗口": ["滑动窗口", "sliding window", "sliding window", "滑动串口"],
        "拥塞控制": ["拥塞控制", "congestion control", "congestion control", "拥se控制"],
        "Nagle": ["nagle", "n a g l e", "奈格欧", "nagle算法"],
        "Keep Alive": ["keepalive", "keep alive", "keep alive", "keep alive"],
        "TIME_WAIT": ["timewait", "time wait", "time wait", "time wait"],
        "CLOSE_WAIT": ["closewait", "close wait", "close wait"],

        # ── 图形学 ──
        "OpenGL": ["opengl", "open gl", "open g l", "欧本gl", "open gl"],
        "Vulkan": ["vulkan", "v u l k a n", "沃肯", "vulkan", "vulkan"],
        "DirectX": ["directx", "direct x", "direct x", "d x", "direct x", "directx"],
        "Metal": ["metal", "m e t a l", "metal", "metal", "metal", "苹果metal"],
        "渲染管线": ["渲染管线", "render pipeline", "render pipeline", "render派普line"],
        "着色器": ["着色器", "shader", "谁的", "shader", "shader"],
        "顶点着色器": ["顶点着色器", "vertex shader", "vertex shader"],
        "片段着色器": ["片段着色器", "fragment shader", "fragment shader", "像素shader"],
        "几何着色器": ["几何着色器", "geometry shader", "geometry shader"],
        "光栅化": ["光栅化", "rasterization", "rasterization", "光山化"],
        "纹理": ["纹理", "texture", "texture", "贴图", "texture"],
        "帧缓冲": ["帧缓冲", "framebuffer", "frame buffer", "frame buffer"],
        "深度测试": ["深度测试", "depth test", "depth test"],
        "模版测试": ["模版测试", "stencil test", "stencil test"],
        "混合": ["混合", "blending", "blending", "布兰丁"],
        "MSAA": ["msaa", "m s a a", "multisample", "msaa", "多重采样"],
        "光线追踪": ["光线追踪", "ray tracing", "ray tracing", "光追", "瑞treacing"],
        "BVH": ["bvh", "b v h", "bounding volume hierarchy", "b v h"],
        "PBR": ["pbr", "p b r", "physically based rendering", "p b r", "基于物理渲染"],

        # ── 游戏引擎 ──
        "Unreal Engine": ["unrealengine", "unreal engine", "unreal", "安瑞欧", "ue", "u e", "ue5", "ue4"],
        "Actor": ["actor", "ac tor", "actor", "爱克特", "actor"],
        "Component": ["component", "com ponent", "component", "康姆剖嫩特"],
        "Blueprint": ["blueprint", "blue print", "blue print", "蓝图", "不露print"],
        "GameMode": ["gamemode", "game mode", "game mode"],
        "GameState": ["gamestate", "game state", "game state"],
        "PlayerController": ["playercontroller", "player controller", "player controller"],
        "Pawn": ["pawn", "p a w n", "pawn", "pawn"],
        "Character": ["character", "cha rac ter", "character", "character", "角色"],
        "Level": ["level", "le vel", "level", "level", "关卡"],
        "World": ["world", "w o r l d", "world", "world"],
        "Tick": ["tick", "t i c k", "tick", "tik"],
        "Delegate": ["delegate", "de le gate", "delegate", "戴利给特"],
        "Interface": ["interface", "inter face", "interface", "interface", "因特face"],
        "UObject": ["uobject", "u object", "u object"],
        "AActor": ["aactor", "a actor", "a actor"],
        "UPROPERTY": ["uproperty", "u property", "u property"],
        "UFUNCTION": ["ufunction", "u function", "u function"],
        "Garbage Collection": ["garbagecollection", "garbage collection", "垃圾回收", "gc"],
        "FString": ["fstring", "f string", "f string"],
        "FName": ["fname", "f name", "f name"],
        "FText": ["ftext", "f text", "f text"],
        "TArray": ["tarray", "t array", "t array"],
        "TMap": ["tmap", "t map", "t map"],
        "TSet": ["tset", "t set", "t set"],
        "Niagara": ["niagara", "ni a ga ra", "奈亚加拉", "niagara"],
        "Nanite": ["nanite", "na nite", "奈耐特", "nanite", "虚拟几何"],
        "Lumen": ["lumen", "lu men", "鲁门", "lumen", "动态全局光照"],
        "Metahuman": ["metahuman", "meta human", "meta human"],

        # ── 音视频 ──
        "FFmpeg": ["ffmpeg", "f f m p e g", "f f mpeg", "ffmpeg"],
        "H.264": ["h264", "h 264", "h点264", "h264"],
        "H.265": ["h265", "h 265", "h点265", "h265", "hevc", "h e v c"],
        "AV1": ["av1", "a v 1", "av1"],
        "编解码": ["编解码", "codec", "codec", "扣戴克", "codec"],
        "流媒体": ["流媒体", "streaming media", "streaming", "streaming media"],
        "RTMP": ["rtmp", "r t m p", "rtmp"],
        "RTSP": ["rtsp", "r t s p", "rtsp"],
        "WebRTC": ["webrtc", "web rtc", "web r t c", "webrtc"],
        "GStreamer": ["gstreamer", "g streamer", "g streamer", "g斯追门"],
        "OpenCV": ["opencv", "open cv", "open c v", "欧本cv", "open cv"],
        "SDL": ["sdl", "s d l", "simple directmedia layer", "s d l"],
        "SFML": ["sfml", "s f m l", "simple fast multimedia", "s f m l"],
        "PCM": ["pcm", "p c m", "pcm"],
        "采样率": ["采样率", "sample rate", "sample rate", "sample rate"],
        "比特率": ["比特率", "bitrate", "bit rate", "bit rate", "码率"],

        # ── 嵌入式 ──
        "RTOS": ["rtos", "r t o s", "real time os", "r t o s", "实时操作系统"],
        "FreeRTOS": ["freertos", "free rtos", "free r t o s", "free rtos"],
        "交叉编译": ["交叉编译", "cross compile", "cross compile", "cross编译"],
        "单片机": ["单片机", "mcu", "m c u", "microcontroller", "单晶片"],
        "ARM": ["arm", "a r m", "arm", "a r m", "arm"],
        "RISC-V": ["riscv", "risc v", "risc five", "risk v", "risk five"],
        "STM32": ["stm32", "s t m 3 2", "stm32"],
        "ESP32": ["esp32", "e s p 3 2", "esp32"],
        "GPIO": ["gpio", "g p i o", "general purpose io", "g p i o"],
        "UART": ["uart", "u a r t", "universal async receiver", "u a r t"],
        "SPI": ["spi", "s p i", "serial peripheral interface", "s p i"],
        "I2C": ["i2c", "i 2 c", "i squared c", "i方c", "iic"],
        "PWM": ["pwm", "p w m", "pulse width modulation", "p w m"],
        "ADC": ["adc", "a d c", "analog to digital", "a d c"],
        "DAC": ["dac", "d a c", "digital to analog", "d a c"],
        "DMA": ["dma", "d m a", "direct memory access", "d m a"],
        "中断向量": ["中断向量", "interrupt vector", "interrupt vector"],
        "Bootloader": ["bootloader", "boot loader", "boot loader", "布特楼的"],
        "Watchdog": ["watchdog", "watch dog", "watch dog", "看门狗"],
        "HAL": ["hal", "h a l", "hardware abstraction layer", "h a l", "硬件抽象层"],

        # ── 性能优化 ──
        "缓存友好": ["缓存友好", "cache friendly", "cache friendly", "cache友好"],
        "缓存行": ["缓存行", "cache line", "cache line", "cache行", "64字节"],
        "伪共享": ["伪共享", "false sharing", "false sharing", "加共享"],
        "分支预测": ["分支预测", "branch prediction", "branch prediction", "分支预ce"],
        "SIMD": ["simd", "s i m d", "single instruction multiple data", "simd"],
        "SSE": ["sse", "s s e", "streaming simd extensions", "s s e"],
        "AVX": ["avx", "a v x", "advanced vector extensions", "a v x"],
        "NEON": ["neon", "n e o n", "neon", "arm neon"],
        "Profile": ["profile", "pro file", "profile", "普若file", "性能分析"],
        "perf": ["perf", "p e r f", "perf", "perf工具"],
        "gprof": ["gprof", "g prof", "g prof"],
        "VTune": ["vtune", "v tune", "v tune", "vtune"],
        "火焰图": ["火焰图", "flame graph", "flame graph", "flame图"],
        "内联": ["内联", "inline", "inline", "in line", "内联展开"],
        "PGO": ["pgo", "p g o", "profile guided optimization", "p g o"],
        "LTO": ["lto", "l t o", "link time optimization", "l t o"],
        "LTO": ["lto", "l t o", "link time optimization", "链接时优化"],

        # ── 测试 ──
        "Google Test": ["googletest", "google test", "google test", "gtest", "g test"],
        "Catch2": ["catch2", "catch 2", "catch two", "catch2"],
        "doctest": ["doctest", "doc test", "doc test", "doctest"],
        "Mock": ["mock", "m o c k", "莫克", "mock", "mock"],
        "GMock": ["gmock", "g mock", "g mock", "google mock"],
        "Stub": ["stub", "s t u b", "stub", "斯达布", "stub"],
        "Fixture": ["fixture", "fix ture", "菲克斯切", "fixture", "fixture"],
        "断言": ["断言", "assert", "assert", "阿色特", "assert"],
        "EXPECT": ["expect", "ex pect", "expect", "expect", "一克斯派克特"],
        "ASSERT": ["assert", "as sert", "assert", "assert"],
        "TDD": ["tdd", "t d d", "test driven development", "t d d"],
        "fuzzing": ["fuzzing", "fuzz testing", "fuzz testing", "模糊测试"],
        "覆盖率": ["覆盖率", "coverage", "coverage", "卡文瑞吉", "覆盖绿"],
        "GCOV": ["gcov", "g cov", "g c o v", "gcov"],
        "LCOV": ["lcov", "l cov", "l c o v", "lcov"],

        # ── 设计模式（C++ 实现） ──
        "单例": ["单例", "单立", "单利", "singleton", "singleton", "辛格腾"],
        "工厂": ["工厂", "factory", "factory", "工厂", "工厂模式"],
        "建造者": ["建造者", "builder", "bill德", "建赵者", "builder"],
        "原型": ["原型", "圆形", "prototype", "普若to type"],
        "观察者": ["观察者", "观察折", "observer", "奥布斯瓦"],
        "策略": ["策略", "strategy", "斯抓特基", "策略模式"],
        "适配器": ["适配器", "adapter", "阿呆普特", "式配器"],
        "装饰器": ["装饰器", "decorator", "呆口瑞特", "装时期"],
        "桥接": ["桥接", "bridge", "布瑞只", "bridge"],
        "组合": ["组合", "composite", "康姆剖色特"],
        "外观": ["外观", "facade", "佛萨德", "facade"],
        "享元": ["享元", "flyweight", "福来未特"],
        "代理": ["代理", "proxy", "普绕克西", "proxy"],
        "命令": ["命令", "command", "康曼的", "command"],
        "中介者": ["中介者", "mediator", "咪迪特", "mediator"],
        "备忘录": ["备忘录", "memento", "memento"],
        "状态": ["状态", "state", "斯得特", "state"],
        "模板方法": ["模板方法", "template method", "坦普雷特method"],
        "访问者": ["访问者", "visitor", "vi洗特"],
        "责任链": ["责任链", "chain of responsibility", "责任连"],
        "迭代器模式": ["迭代器模式", "iterator pattern", "iterator"],
        "解释器": ["解释器", "interpreter", "interpreter", "因特普瑞特"],
        "CRTP": ["crtp", "c r t p", "curiously recurring template", "c r t p", "奇异递归模板"],

        # ── 杂项 ──
        "序列化": ["序列化", "serialization", "希尔莱z神", "序列画"],
        "反序列化": ["反序列化", "deserialization", "反序列画"],
        "Protobuf": ["protobuf", "proto buf", "普若托buf", "protobuf"],
        "FlatBuffers": ["flatbuffers", "flat buffers", "flat buffers"],
        "MessagePack": ["messagepack", "message pack", "message pack"],
        "JSON": ["json", "j s o n", "杰森", "jason"],
        "XML": ["xml", "x m l", "叉ml", "xml"],
        "YAML": ["yaml", "y a m l", "雅某"],
        "日志": ["日志", "log", "log", "劳格", "log"],
        "spdlog": ["spdlog", "spd log", "speed log", "spdlog"],
        "glog": ["glog", "g log", "g log", "google log"],
        "多线程": ["多线程", "multithreading", "马欧体斯瑞丁"],
        "多进程": ["多进程", "multiprocessing", "马欧体普若赛斯"],
        "异常": ["异常", "exception", "一克斯赛普神"],
        "异常安全": ["异常安全", "exception safety", "exception safe", "异常完全"],
        "noexcept": ["noexcept", "no except", "no except", "no except"],
        "RTTI": ["rtti", "r t t i", "run time type info", "r t t i"],
        "typeid": ["typeid", "type id", "type id"],
        "dynamic_cast": ["dynamiccast", "dynamic cast", "dynamic cast", "dynamic cast"],
        "static_cast": ["staticcast", "static cast", "static cast"],
        "reinterpret_cast": ["reinterpretcast", "reinterpret cast", "reinterpret cast"],
        "const_cast": ["constcast", "const cast", "const cast"],
        "友元": ["友元", "friend", "friend", "friend", "friend", "朋友类"],
        "命名空间": ["命名空间", "namespace", "namespace", "内姆space"],
        "using": ["using", "u s i n g", "using", "using关键字", "using"],
        "typedef": ["typedef", "type def", "type def", "taip def"],
        "using": ["using", "using", "using语句", "u s i n g"],
        "enum class": ["enumclass", "enum class", "enum class", "强类型枚举"],

        # ── C++17/20/23 新特性 ──
        "filesystem": ["filesystem", "file system", "file system", "fs", "f s", "文件系统", "std::filesystem"],
        "std::filesystem": ["stdfilesystem", "std filesystem", "s t d filesystem"],
        "regex": ["regex", "r e g e x", "瑞杰克斯", "正则", "std::regex", "正则库"],
        "std::regex": ["stdregex", "std regex", "s t d regex"],
        "chrono": ["chrono", "c h r o n o", "克若no", "std::chrono", "时间库"],
        "std::chrono": ["stdchrono", "std chrono", "s t d chrono"],
        "steady_clock": ["steadyclock", "steady clock", "steady clock", "稳定时钟"],
        "system_clock": ["systemclock", "system clock", "system clock", "系统时钟"],
        "duration": ["duration", "du ra tion", "duration", "丢瑞神", "时间段"],
        "time_point": ["timepoint", "time point", "time point", "时间点"],
        "random": ["random", "ran dom", "软dom", "随机", "std::random", "random库"],
        "random_device": ["randomdevice", "random device", "random device", "硬件随机"],
        "mt19937": ["mt19937", "m t 19937", "m t 19937", "梅森旋转", "mersenne twister"],
        "uniform_int_distribution": ["uniformint", "uniform int", "uniform int distribution", "均匀整数分布"],
        "format": ["format", "for mat", "format", "格式化", "std::format", "format", "c++20format"],
        "std::format": ["stdformat", "std format", "s t d format"],
        "source_location": ["sourcelocation", "source location", "source location", "std::source_location"],
        "expected": ["expected", "ex pect ed", "expected", "std::expected", "一克斯派克特", "expected类", "c++23expected"],
        "std::expected": ["stdexpected", "std expected", "s t d expected"],
        "mdspan": ["mdspan", "m d span", "md span", "多维span", "std::mdspan"],
        "flat_map": ["flatmap", "flat map", "flat map", "flat map", "std::flat_map"],
        "flat_set": ["flatset", "flat set", "flat set", "std::flat_set"],
        "generator": ["generator", "gen er ator", "generator", "std::generator", "生成器"],
        "deduction guide": ["deductionguide", "deduction guide", "推导指引", "推倒指引"],
        "CTAD": ["ctad", "c t a d", "class template argument deduction", "c t a d"],
        "if constexpr": ["ifconstexpr", "if constexpr", "if const expr", "编译期if"],
        "fold expression": ["foldexpression", "fold expression", "折叠表达式"],
        "designated initializer": ["designatedinitializer", "designated initializer", "指定初始化"],
        "explicit": ["explicit", "ex pli cit", "explicit", "一克斯普利斯", "explicit关键字"],
        "noexcept": ["noexcept", "no except", "no except", "不抛出"],
        "nodiscard": ["nodiscard", "no discard", "no discard", "不丢弃"],
        "likely": ["likely", "like ly", "likely", "likely", "可能"],
        "unlikely": ["unlikely", "un like ly", "unlikely", "不可能"],

        # ── 智能指针 / 内存补充 ──
        "make_unique": ["makeunique", "make unique", "make unique", "std::make_unique"],
        "make_shared": ["makeshared", "make shared", "make shared", "std::make_shared"],
        "enable_shared_from_this": ["enablesharedfromthis", "enable shared from this", "enable shared from this"],
        "weak_ptr.lock": ["weakptrlock", "weak ptr lock", "weak_ptr::lock", "weak lock"],
        "destructor": ["destructor", "de struc tor", "析构函数", "deep斯抓克特", "destructor", "析构"],
        "constructor": ["constructor", "con struc tor", "构造函数", "康思抓克特", "构造函数"],
        "PIMPL": ["pimpl", "p i m p l", "pimpl", "pointer to implementation", "p i m p l", "编译防火墙"],
        "NVI": ["nvi", "n v i", "non virtual interface", "n v i", "非虚接口"],
        "invoke": ["invoke", "in voke", "invoke", "因vo克", "std::invoke"],
        "std::invoke": ["stdinvoke", "std invoke", "s t d invoke"],
        "apply": ["apply", "ap ply", "apply", "std::apply"],
        "std::apply": ["stdapply", "std apply", "s t d apply"],
        "exchange": ["exchange", "ex change", "exchange", "std::exchange", "一克斯change"],
        "clamp": ["clamp", "c l a m p", "clamp", "std::clamp", "克烂p"],
        "std::function": ["stdfunction", "std function", "s t d function", "std方格申"],
        "std::bind": ["stdbind", "std bind", "s t d bind", "std bind"],
        "std::ref": ["stdref", "std ref", "s t d ref", "std ref"],
        "std::cref": ["stdcref", "std cref", "s t d cref"],
        "stringstream": ["stringstream", "string stream", "stringstream", "字符串流", "stringstream"],
        "ostringstream": ["ostringstream", "o stringstream", "输出stringstream", "ostringstream"],
        "istringstream": ["istringstream", "i stringstream", "输入stringstream"],
        "to_string": ["tostring", "to string", "to string", "std::to_string"],
        "stoi": ["stoi", "s t o i", "string to int", "s t o i"],
        "stod": ["stod", "s t o d", "string to double", "s t o d"],
        "cin": ["cin", "c in", "c in", "标准输入", "see in"],
        "cout": ["cout", "c out", "c out", "标准输出", "see out"],
        "cerr": ["cerr", "c err", "c err", "标准错误", "see err"],
        "ifstream": ["ifstream", "i f stream", "ifstream", "input file stream"],
        "ofstream": ["ofstream", "o f stream", "ofstream", "output file stream"],
        "getline": ["getline", "get line", "get line", "getline", "std::getline"],
        "bitset": ["bitset", "bit set", "bit set", "std::bitset", "位集"],
        "valarray": ["valarray", "val array", "val array", "std::valarray"],
        "visit": ["visit", "vi sit", "visit", "std::visit", "访问"],
        "std::visit": ["stdvisit", "std visit", "s t d visit"],

        # ── 并发补充 ──
        "shared_mutex": ["sharedmutex", "shared mutex", "shared mutex", "std::shared_mutex"],
        "timed_mutex": ["timedmutex", "timed mutex", "timed mutex", "std::timed_mutex"],
        "recursive_mutex": ["recursivemutex", "recursive mutex", "递归mutex", "std::recursive_mutex"],
        "call_once": ["callonce", "call once", "call once", "std::call_once"],
        "once_flag": ["onceflag", "once flag", "once flag", "std::once_flag"],
        "counting_semaphore": ["countingsemaphore", "counting semaphore", "计数semaphore"],
        "binary_semaphore": ["binarysemaphore", "binary semaphore", "二元semaphore"],
        "hardware_destructive_interference_size": ["hardwaredestructive", "hardware destructive", "硬件破坏干扰"],
        "hardware_constructive_interference_size": ["hardwareconstructive", "hardware constructive"],
        "memory fence": ["memoryfence", "memory fence", "memory barrier", "内存栅栏", "内存屏障"],
        "acquire": ["acquire", "ac quire", "阿快尔", "acquire", "获取"],
        "release": ["release", "re lease", "release", "瑞lis", "释放"],
        "relaxed": ["relaxed", "re laxed", "relaxed", "瑞莱克斯", "宽松"],
        "seq_cst": ["seqcst", "seq cst", "sequential consistency", "顺序一致"],
        "double-checked locking": ["doublecheckedlocking", "double checked locking", "双重检查锁", "DCL", "d c l"],

        # ── Type Traits ──
        "type_traits": ["typetraits", "type traits", "type traits", "类型萃取", "type properties"],
        "enable_if": ["enableif", "enable if", "enable if", "std::enable_if", "e nable if"],
        "void_t": ["voidt", "void t", "void t", "std::void_t"],
        "is_same": ["issame", "is same", "is same", "std::is_same"],
        "is_base_of": ["isbaseof", "is base of", "is base of", "std::is_base_of"],
        "is_convertible": ["isconvertible", "is convertible", "is convertible"],
        "decay_t": ["decayt", "decay t", "decay t", "std::decay_t", "退化"],
        "remove_reference": ["removereference", "remove reference", "remove reference"],
        "conditional": ["conditional", "con di tion al", "conditional", "std::conditional"],
        "underlying_type": ["underlyingtype", "underlying type", "底层类型"],

        # ── 异常 / 错误处理 ──
        "try/catch": ["trycatch", "try catch", "try catch", "揣catch"],
        "throw": ["throw", "t h r o w", "throw", "斯肉", "抛出异常"],
        "exception": ["exception", "ex cep tion", "exception", "一克斯赛普神", "异常"],
        "runtime_error": ["runtimeerror", "runtime error", "runtime error", "std::runtime_error"],
        "logic_error": ["logicerror", "logic error", "logic error", "std::logic_error"],
        "out_of_range": ["outofrange", "out of range", "out of range", "越界"],
        "bad_alloc": ["badalloc", "bad alloc", "bad alloc", "std::bad_alloc"],
        "bad_cast": ["badcast", "bad cast", "bad cast", "std::bad_cast"],
        "catch": ["catch", "c a t c h", "catch", "catch", "开吃", "捕获"],
        "rethrow": ["rethrow", "re throw", "re throw", "重抛出"],
        "stack unwinding": ["stackunwinding", "stack unwinding", "栈展开", "stack unwind"],
        "RAII与异常": ["raii与异常", "raii exception", "raii exception safety"],
        "strong guarantee": ["strongguarantee", "strong guarantee", "强保证"],
        "basic guarantee": ["basicguarantee", "basic guarantee", "基本保证"],
        "nothrow guarantee": ["nothrowguarantee", "nothrow guarantee", "不抛出保证"],

        # ── ABI / 编译补充 ──
        "ABI": ["abi", "a b i", "application binary interface", "a b i", "二进制接口"],
        "Name Mangling": ["namemangling", "name mangling", "名字修饰", "名称改编"],
        "extern C": ["externc", "extern c", "extern c", "extern \"C\"", "c链接"],
        "calling convention": ["callingconvention", "calling convention", "调用约定"],
        "cdecl": ["cdecl", "c decl", "c calling convention", "c decl"],
        "stdcall": ["stdcall", "std call", "std call", "stdcall"],
        "fastcall": ["fastcall", "fast call", "fast call"],
        "thiscall": ["thiscall", "this call", "this call"],
        "ODR": ["odr", "o d r", "one definition rule", "o d r", "单一定义规则"],  # already above, fine to repeat
        "COMDAT": ["comdat", "c o m d a t", "comdat"],
        "Visibility": ["visibility", "vi si bility", "visibility", "可见性", "符号可见性"],
        "dllexport": ["dllexport", "dll export", "dll export"],
        "dllimport": ["dllimport", "dll import", "dll import"],
        "强符号": ["强符号", "strong symbol", "strong symbol"],
        "弱符号": ["弱符号", "weak symbol", "weak symbol"],

        # ── 包管理 / 工具 ──
        "vcpkg": ["vcpkg", "v c p k g", "vc pkg", "vcpkg", "微软vcpkg"],
        "Conan": ["conan", "c o n a n", "柯南", "conan", "conan包管理"],
        "clang-format": ["clangformat", "clang format", "clang format", "clang格式化"],
        "clang-tidy": ["clangtidy", "clang tidy", "clang tidy", "clang检查"],
        "cppcheck": ["cppcheck", "cpp check", "c++ check", "cppcheck"],
        "iwyu": ["iwyu", "i w y u", "include what you use", "i w y u"],
        "CCache": ["ccache", "c cache", "c cache", "编译缓存"],
        "distcc": ["distcc", "dist cc", "dist cc", "分布式编译"],
        "scan-build": ["scanbuild", "scan build", "scan build"],
        "Doxygen": ["doxygen", "dox y gen", "道可森", "doxygen", "文档生成"],
        "GDB": ["gdb", "g d b", "g d b", "gdb调试"],
        "LLDB": ["lldb", "l l d b", "l l d b", "lldb调试"],
        "WinDbg": ["windbg", "win dbg", "win debug", "windbg"],
        "coredump": ["coredump", "core dump", "core dump", "核心转储", "扣dump"],

        # ── Qt 框架 ──
        "Qt": ["qt", "q t", "Q T", "qt框架", "q t框架", "QT"],
        "QWidget": ["qwidget", "q widget", "q widget", "q widget"],
        "QML": ["qml", "q m l", "q m l", "qml"],
        "Signal/Slot": ["signalslot", "signal slot", "signal slot", "信号槽", "signal slot"],
        "QObject": ["qobject", "q object", "q object"],
        "QApplication": ["qapplication", "q application", "q application"],
        "QPushButton": ["qpushbutton", "q pushbutton", "q pushbutton"],
        "QMainWindow": ["qmainwindow", "q mainwindow", "q mainwindow"],
        "QLayout": ["qlayout", "q layout", "q layout"],
        "MOC": ["moc", "m o c", "meta object compiler", "m o c", "元对象编译器"],
        "Qt Quick": ["qtquick", "qt quick", "qt快速"],
        "Qt Creator": ["qtcreator", "qt creator", "qt创建器"],

        # ── Boost 补充 ──
        "Boost": ["boost", "b o o s t", "布斯特", "boost库", "boost"],
        "Boost.Asio": ["boostasio", "boost asio", "boost asio"],
        "Boost.Beast": ["boostbeast", "boost beast", "boost beast"],
        "Boost.Filesystem": ["boostfilesystem", "boost filesystem", "boost fs"],
        "Boost.Spirit": ["boostspirit", "boost spirit", "boost spirit"],
        "Boost.Python": ["boostpython", "boost python", "boost python"],
        "Boost.Serialization": ["boostserialization", "boost serialization", "boost序列化"],
        "Boost.Test": ["boosttest", "boost test", "boost test"],
        "Boost.Graph": ["boostgraph", "boost graph", "boost graph"],
        "Boost.ProgramOptions": ["boostprogramoptions", "boost program options"],

        # ── 编译选项 ──
        "编译器优化": ["编译器优化", "compiler optimization", "编译优化"],
        "优化等级": ["优化等级", "optimization level", "O0", "O1", "O2", "O3", "Os", "Oz"],
        "Debug": ["debug", "de bug", "debug", "调试", "debug模式", "debug"],
        "Release": ["release", "re lease", "release", "发布模式", "瑞lis"],
        "Wall": ["wall", "w all", "w all", "Wall", "所有警告", "威all"],
        "Wextra": ["wextra", "w extra", "w extra", "Wextra"],
        "Werror": ["werror", "w error", "w error", "警告即错误"],
        "fPIC": ["fpic", "f p i c", "fpic", "位置无关代码"],
        "fno-rtti": ["fnortti", "fno rtti", "f no rtti", "禁用rtti"],
        "fno-exceptions": ["fnoexceptions", "fno exceptions", "禁用异常"],
        "fsanitize": ["fsanitize", "f sanitize", "fsanitize", "fsanitize=address"],
        "fprofile-generate": ["fprofilegenerate", "fprofile generate"],
        "flto": ["flto", "f lto", "flto", "链接时优化"],  # already have LTO above

        # ── 杂项补充 ──
        "四则转换": ["四则转换", "four casts", "四种cast", "四个cast"],
        "explicit转换": ["explicit转换", "explicit cast", "explicit转换"],
        "implicit转换": ["implicit转换", "implicit cast", "隐式转换"],
        "窄化转换": ["窄化转换", "narrowing conversion", "narrowing"],
        "用户定义字面量": ["用户定义字面量", "user defined literal", "user literal", "自定义字面量"],
        "attribute": ["attribute", "at tribute", "阿吹标"],
        "deprecated": ["deprecated", "de pre cat ed", "deprecated", "已弃用"],
        "maybe_unused": ["maybeunused", "maybe unused", "maybe unused"],
        "fallthrough": ["fallthrough", "fall through", "fall through"],
        "nodiscard": ["nodiscard", "no discard", "no discard", "不丢弃"],
        "三向比较": ["三向比较", "three way comparison", "飞船运算符"],
        "POD": ["pod", "p o d", "plain old data", "p o d"],
        "trivial": ["trivial", "tri vial", "trivial", "平凡", "trivial类"],
        "standard layout": ["standardlayout", "standard layout", "标准布局"],
        "aggregate": ["aggregate", "ag gre gate", "aggregate", "聚合类"],
        "literal type": ["literaltype", "literal type", "literal type", "字面量类型"],
        "volatile": ["volatile", "vo la tile", "volatile", "沃了太欧", "volatile"],
        "mutable": ["mutable", "mu ta ble", "mutable", "谬特波"],
        "register": ["register", "re gis ter", "register", "寄存器", "爱吉斯特"],
        "restrict": ["restrict", "re strict", "restrict", "限制"],
        "alignas": ["alignas", "a lign as", "align as", "对齐"],
        "alignof": ["alignof", "a lign of", "align of", "对齐查询"],
    },
}
