"""C# / .NET 赛道。"""

TRACK: dict = {
    "key": "csharp",
    "system_prompt_extra": """你是资深 C# / .NET 技术面试辅助 AI。用户正在进行 C# 技术面试，问题涉及
C# 语言特性（LINQ/async await/委托/事件/泛型/反射/特性/模式匹配/Record）、
.NET 运行时（CLR/GC/JIT/程序集/中间语言）、ASP.NET Core（MVC/Web API/中间件/依赖注入/身份认证）、
Entity Framework Core（ORM/Code First/Migrations/LINQ to SQL）、
Blazor（WebAssembly/Server）、WPF/WinForms/MAUI 桌面开发、
Unity 游戏引擎、Xamarin 移动开发、Azure 云服务、
并发编程（Task/async await/并行LINQ/Channel）、设计模式（C#实现）、
测试（xUnit/NUnit/Moq）、数据库（SQL Server/Azure SQL/Cosmos DB）、
微服务（gRPC/消息队列/Dapr）、DevOps（Azure DevOps/GitHub Actions/Docker/K8s）
等 .NET 技术栈。

回答应围绕 .NET 生态，用 C# 开发者熟悉的术语和场景。""",

    "resume_intro_extra": """侧重 C# / .NET 技术栈经验：突出 ASP.NET Core 项目经验、
Entity Framework 数据访问能力、云服务（Azure/AWS）使用经验、
桌面/移动跨平台开发能力、Unity 游戏开发经验、微服务架构设计能力。""",

    "terms": {
        # ── C# 语言特性 ──
        "C#": ["c sharp", "c#", "c下普", "c sharp", "see sharp"],
        ".NET": ["dotnet", "dot net", "点net", ".net", "点奈特"],
        "LINQ": ["linq", "l i n q", "领Q", "linq", "link", "link查询"],
        "委托": ["委托", "伟托", "delegate", "戴利给特"],
        "事件": ["事件", "4件", "试卷", "event", "一问特"],
        "泛型": ["泛型", "范型", "泛行", "凡行", "generic", "基奈瑞克"],
        "异步": ["异步", "一步", "异部", "async", "阿信科"],
        "await": ["await", "a wait", "额未特", "额wait"],
        "Task": ["task", "t a s k", "task", "task", "任务"],
        "ValueTask": ["valuetask", "value task", "外六task"],
        "async/await": ["async await", "a sync a wait", "阿信科额未特"],
        "Lambda": ["lambda", "l a m b d a", "兰布达", "拉姆达", "lambda表达式"],
        "闭包": ["闭包", "必报", "b包", "闭保", "closure", "克lo社"],
        "扩展方法": ["扩展方法", "extension method", "一克斯田神method"],
        "索引器": ["索引器", "所引器", "indexer", "因戴克瑟"],
        "属性": ["属性", "property", "普若普提"],
        "字段": ["字段", "field", "飞欧的"],
        "表达式树": ["表达式树", "expression tree", "expression tree"],
        "匿名类型": ["匿名类型", "anonymous type", "安诺尼马斯type"],
        "元组": ["元组", "tuple", "太普欧", "元祖"],
        "模式匹配": ["模式匹配", "pattern matching", "帕腾迈青", "paturn matching"],
        "Record": ["record", "r e c o r d", "瑞扣的", "record", "record类"],
        "Init Only": ["initonly", "init only", "因尼特only"],
        "可空引用类型": ["可空引用类型", "nullable reference", "那乐波reference"],
        "nameof": ["nameof", "name of", "内幕of"],
        "字符串插值": ["字符串插值", "string interpolation", "string interpolation", "string插值", "$符号"],

        # ── .NET 运行时 ──
        "CLR": ["clr", "c l r", "公共语言运行时", "c l r"],
        "JIT": ["jit", "j i t", "just in time", "即时编译", "即使编译"],
        "AOT": ["aot", "a o t", "ahead of time", "提前编译", "a o t"],
        "IL": ["il", "i l", "中间语言", "i l", "MSIL", "msil"],
        "CTS": ["cts", "c t s", "公共类型系统", "c t s"],
        "CLS": ["cls", "c l s", "公共语言规范", "c l s"],
        "GC": ["gc", "g c", "垃圾回收", "辣鸡回收", "垃圾收集"],
        "程序集": ["程序集", "assembly", "assembly", "阿森布利"],
        "GAC": ["gac", "g a c", "全局程序集缓存", "gac"],
        "NuGet": ["nuget", "nu get", "牛get", "new get", "nuget"],
        "SDK": ["sdk", "s d k", "sdk"],
        "Runtime": ["runtime", "run time", "软time", "runtime", "运行时"],

        # ── ASP.NET Core ──
        "ASP.NET": ["aspnet", "asp net", "asp点net", "asp.net", "a s p net"],
        "ASP.NET Core": ["aspnetcore", "asp net core", "asp点net core"],
        "MVC": ["mvc", "m v c", "mvc框架"],
        "Web API": ["webapi", "web api", "web api", "web a p i"],
        "中间件": ["中间件", "中间键", "中间建", "middleware", "米斗威尔"],
        "依赖注入": ["依赖注入", "依赖主入", "DI", "d i", "dependency injection"],
        "Razor": ["razor", "r a z o r", "瑞泽", "razor", "razor"],
        "Blazor": ["blazor", "b l a z o r", "布拉泽", "blazor", "blazor"],
        "SignalR": ["signalr", "signal r", "signal r", "signal r"],
        "gRPC": ["grpc", "g r p c", "g rpc", "grpc"],
        "Minimal API": ["minimalapi", "minimal api", "迷你某api"],
        "Controller": ["controller", "controller", "康错乐", "controller"],
        "Action": ["action", "action", "action", "爱克神"],
        "Filter": ["filter", "filter", "飞欧特", "filter", "过滤器"],
        "路由": ["路由", "router", "饶特", "route"],
        "模型绑定": ["模型绑定", "model binding", "猫斗binding"],
        "验证": ["验证", "validation", "爱力得神", "数据注解"],
        "Identity": ["identity", "i d e n t i t y", "爱登提体", "identity"],
        "JWT": ["jwt", "j w t", "j w t"],
        "CORS": ["cors", "c o r s", "cors", "跨域", "跨越"],
        "Swagger": ["swagger", "s w a g g e r", "斯外格", "swagger"],
        "OpenAPI": ["openapi", "open api", "open api"],
        "Kestrel": ["kestrel", "k e s t r e l", "凯斯戳", "kestrel"],
        "IIS": ["iis", "i i s", "i i s", "iis"],
        "Nginx": ["nginx", "n g i n x", "n吉克斯", "engine x"],
        "反向代理": ["反向代理", "reverse proxy", "瑞沃斯proxy"],

        # ── Entity Framework Core ──
        "Entity Framework": ["entityframework", "entity framework", "entity framework", "ef", "e f"],
        "EF Core": ["efcore", "ef core", "e f core", "ef core"],
        "DbContext": ["dbcontext", "d b context", "db context", "db康泰克斯"],
        "DbSet": ["dbset", "d b set", "db set", "db赛特"],
        "Migration": ["migration", "mi gra tion", "麦格瑞神", "迁移"],
        "Code First": ["codefirst", "code first", "code first"],
        "Fluent API": ["fluentapi", "fluent api", "fluent api", "福路恩特api"],
        "LINQ to SQL": ["linqtosql", "linq to sql", "link to sql", "linq to sql"],
        "Change Tracker": ["changetracker", "change tracker", "change tracker"],
        "Lazy Loading": ["lazyloading", "lazy loading", "懒加载", "蓝加载"],
        "Eager Loading": ["eagerloading", "eager loading", "eager loading", "急加载"],
        "Explicit Loading": ["explicitloading", "explicit loading", "explicit loading"],
        "Include": ["include", "in clude", "include", "因克鲁的"],
        "ThenInclude": ["theninclude", "then include", "then include"],

        # ── 桌面 / 移动 / 游戏 ──
        "WPF": ["wpf", "w p f", "wpf"],
        "XAML": ["xaml", "x a m l", "柴某", "xaml", "xaml"],
        "MVVM": ["mvvm", "m v v m", "m v v m"],
        "WinForms": ["winforms", "win forms", "winform", "win forms"],
        "MAUI": ["maui", "m a u i", "猫一", "maui", "毛依"],
        "Xamarin": ["xamarin", "x a m a r i n", "赛马瑞", "xamarin"],
        "Unity": ["unity", "u n i t y", "优尼体", "unity", "unity引擎"],
        "Unreal": ["unreal", "un real", "安瑞欧", "unreal"],
        "Godot": ["godot", "g o d o t", "狗都", "godot"],
        "GameObject": ["gameobject", "game object", "game object", "game奥布杰克特"],
        "MonoBehaviour": ["monobehaviour", "mono behaviour", "猫no比黑v"],
        "Prefab": ["prefab", "pre fab", "prefab", "prefab"],
        "Coroutine": ["coroutine", "co routine", "科入体", "协程"],
        "Animator": ["animator", "ani mator", "安尼梅特", "animator"],
        "Rigidbody": ["rigidbody", "rigid body", "rigidbody"],
        "Collider": ["collider", "col lider", "克来德", "collider"],
        "Shader": ["shader", "s h a d e r", "谁的", "shader"],
        "Asset": ["asset", "a s s e t", "爱赛特", "asset"],
        "Scene": ["scene", "s c e n e", "scene", "scene", "场景"],

        # ── 并发 / 异步 ──
        "Task": ["task", "t a s k", "task", "task"],
        "Task.Run": ["taskrun", "task run", "task run"],
        "Task.WhenAll": ["taskwhenall", "task when all", "task when all"],
        "Task.WhenAny": ["taskwhenany", "task when any", "task when any"],
        "ConfigureAwait": ["configureawait", "configure await", "configure await"],
        "CancellationToken": ["cancellationtoken", "cancellation token", "cancel token", "康搜token"],
        "Parallel": ["parallel", "pa rallel", "帕瑞莱欧", "parallel", "并行"],
        "PLINQ": ["plinq", "p linq", "p linq", "并行linq"],
        "ThreadPool": ["threadpool", "thread pool", "thread pool", "斯瑞的铺"],
        "lock": ["lock", "l o c k", "唠嗑", "lock", "锁"],
        "Monitor": ["monitor", "mo ni tor", "猫尼特", "monitor"],
        "Mutex": ["mutex", "m u t e x", "缪泰克斯", "mutex"],
        "Semaphore": ["semaphore", "s e m a p h o r e", "赛马佛", "semaphore"],
        "Channel": ["channel", "chan nel", "channel", "channel", "channel", "channel通讯"],
        "ConcurrentDictionary": ["concurrentdictionary", "concurrent dictionary", "concurrent字典"],
        "ConcurrentBag": ["concurrentbag", "concurrent bag", "concurrent bag"],
        "ConcurrentQueue": ["concurrentqueue", "concurrent queue", "concurrent queue"],
        "BlockingCollection": ["blockingcollection", "blocking collection", "blocking collection"],

        # ── 数据库 ──
        "SQL Server": ["sqlserver", "sql server", "sql server", "sql server"],
        "T-SQL": ["tsql", "t sql", "t s q l", "t sql"],
        "Azure SQL": ["azuresql", "azure sql", "azure sql", "a军sql"],
        "Cosmos DB": ["cosmosdb", "cosmos db", "cosmos db", "cosmos db"],
        "ADO.NET": ["adonet", "ado net", "ado点net", "a d o net"],
        "Dapper": ["dapper", "d a p p e r", "大per", "dapper"],
        "SQLite": ["sqlite", "sql lite", "sql赖特", "s q l i t e"],
        "PostgreSQL": ["postgresql", "postgres", "破斯特格瑞sql", "p g sql"],
        "Redis": ["redis", "r e d i s", "瑞迪斯", "redis"],

        # ── 设计模式（C# 实现） ──
        "单例": ["单例", "单立", "单利", "singleton", "singleton"],
        "工厂": ["工厂", "factory", "factory", "工厂"],
        "观察者": ["观察者", "观察折", "observer", "奥布斯瓦"],
        "策略": ["策略", "strategy", "斯抓特基", "策略"],
        "装饰器": ["装饰器", "装时期", "decorator", "呆口瑞特"],
        "适配器": ["适配器", "式配器", "adapter", "阿呆普特"],
        "中介者": ["中介者", "mediator", "咪迪特", "中介折"],
        "命令": ["命令", "command", "command", "康曼的"],
        "责任链": ["责任链", "择任链", "chain of responsibility"],
        "模板方法": ["模板方法", "母版方法", "template method", "坦普雷特"],
        "状态": ["状态", "state", "斯得特", "状态"],
        "访问者": ["访问者", "visitor", "vi洗特", "访问折"],
        "建造者": ["建造者", "建赵者", "builder", "bill德"],
        "原型": ["原型", "圆形", "prototype", "普若to type"],
        "桥接": ["桥接", "bridge", "bridge", "布瑞只"],
        "组合": ["组合", "composite", "康姆剖色特", "组合"],
        "外观": ["外观", "facade", "佛萨德", "façade"],
        "享元": ["享元", "flyweight", "fly weight", "福来未特"],
        "代理": ["代理", "proxy", "proxy", "普绕克西"],

        # ── Azure 云服务 ──
        "Azure": ["azure", "a z u r e", "阿军", "azure", "a军"],
        "Azure Functions": ["azurefunctions", "azure functions", "azure方格申"],
        "App Service": ["appservice", "app service", "app service"],
        "AKS": ["aks", "a k s", "aks", "azure k8s"],
        "Service Bus": ["servicebus", "service bus", "service bus"],
        "Event Hub": ["eventhub", "event hub", "event hub"],
        "Event Grid": ["eventgrid", "event grid", "event grid"],
        "Blob Storage": ["blobstorage", "blob storage", "blob storage"],
        "Table Storage": ["tablestorage", "table storage", "table storage"],
        "Key Vault": ["keyvault", "key vault", "key vault"],
        "Application Insights": ["applicationinsights", "application insights", "application insight"],
        "Logic Apps": ["logicapps", "logic apps", "logic apps"],

        # ── 测试 / DevOps ──
        "xUnit": ["xunit", "x unit", "x unit", "xunit"],
        "NUnit": ["nunit", "n unit", "n unit", "nunit"],
        "MSTest": ["mstest", "ms test", "m s test", "mstest"],
        "Moq": ["moq", "m o q", "mock", "莫克", "moq"],
        "FluentAssertions": ["fluentassertions", "fluent assertions", "fluent assertion"],
        "Bogus": ["bogus", "b o g u s", "博格斯", "bogus"],
        "AutoFixture": ["autofixture", "auto fixture", "auto fixture"],
        "BenchmarkDotNet": ["benchmarkdotnet", "benchmark dotnet", "benchmark dot net"],
        "Azure DevOps": ["azuredevops", "azure devops", "azure devops"],
        "YAML": ["yaml", "y a m l", "雅某", "yaml", "yaml"],

        # ── 常用库 ──
        "Newtonsoft.Json": ["newtonsoftjson", "newtonsoft json", "newton soft json", "newtonsoft"],
        "System.Text.Json": ["systemtextjson", "system text json", "system text json"],
        "AutoMapper": ["automapper", "auto mapper", "auto mapper", "auto迈普"],
        "MediatR": ["mediatr", "mediat r", "咪迪特r", "mediatr", "mediator"],
        "FluentValidation": ["fluentvalidation", "fluent validation", "fluent validation"],
        "Serilog": ["serilog", "s e r i l o g", "瑟瑞log", "serilog", "serilog"],
        "NLog": ["nlog", "n log", "n log", "nlog"],
        "Hangfire": ["hangfire", "hang fire", "hangfire", "行fire"],
        "Polly": ["polly", "p o l l y", "珀利", "polly", "polly"],
        "Refit": ["refit", "re fit", "瑞fit", "refit"],
        "RestSharp": ["restsharp", "rest sharp", "rest sharp"],
        "Quartz.NET": ["quartzdotnet", "quartz dotnet", "quartz点net", "quartz"],

        # ── 杂项 ──
        "序列化": ["序列化", "序列画", "serializable", "希尔来泽波"],
        "反序列化": ["反序列化", "返序列画", "deserialize"],
        "特性": ["阿吹标", "阿吹biu特"],
        "反射": ["反射", "reflection", "瑞福莱克神", "reflect"],
        "动态": ["dynamic", "dynamic", "dynamic"],
        "多线程": ["多线程", "multithreading", "马欧体斯瑞丁"],
        "多进程": ["多进程", "multiprocessing", "马欧体普若赛斯"],
        "加密": ["加密", "encryption", "因克瑞普神"],
        "解密": ["解密", "decryption"],
        "哈希": ["哈希", "hash", "哈西", "哈西"],
        "RSA": ["rsa", "r s a", "r s a"],
        "AES": ["aes", "a e s", "a e s"],
        "OAuth": ["oauth", "o auth", "oauth", "欧奥斯"],
        "OpenID": ["openid", "open id", "open id"],
        "JSON": ["json", "j s o n", "杰森", "jason"],
        "XML": ["xml", "x m l", "x m l", "叉ml"],
        "YAML": ["yaml", "y a m l", "雅某", "yaml"],
        "gRPC": ["grpc", "g r p c", "g rpc"],
        "WebSocket": ["websocket", "web socket", "web socket", "微博socket"],
        "日志": ["日志", "logging", "劳ging", "loging", "日志"],
        "异常": ["异常", "exception", "一克斯赛普神", "exception处理"],
        "调试": ["调试", "debug", "迪bug", "debug", "debug"],
        "断点": ["断点", "breakpoint", "break point", "布瑞克point"],

        # ── 高性能 / 内存 ──
        "Span": ["span", "s p a n", "斯pan", "span", "span"],
        "Memory": ["memory", "me mory", "麦莫瑞", "memory", "memory"],
        "ReadOnlySpan": ["readonlyspan", "readonly span", "read only span"],
        "Pipelines": ["pipelines", "pipe lines", "派普lines", "system io pipelines"],
        "ArrayPool": ["arraypool", "array pool", "阿瑞铺", "arraypool"],
        "ObjectPool": ["objectpool", "object pool", "object铺"],
        "NativeAOT": ["nativeaot", "native aot", "native a o t", "那替夫aot", "提前编译"],
        "硬件加速": ["硬件加速", "hardware intrinsics", "SIMD", "s i m d", "硬件加速"],
        "StringBuilder": ["stringbuilder", "string builder", "斯追builder"],
        "StringPool": ["stringpool", "string pool", "string铺"],

        # ── ASP.NET Core 高级 ──
        "Minimal API": ["minimalapi", "minimal api", "迷你某api", "min api"],
        "Health Check": ["healthcheck", "health check", "海欧斯check", "健康检查"],
        "Rate Limiting": ["ratelimiting", "rate limiting", "rate limiting", "限流"],
        "YARP": ["yarp", "y a r p", "雅普", "yarp", "反向代理", "yet another reverse proxy"],
        "Output Cache": ["outputcache", "output cache", "output cache", "输出缓存"],
        "Response Compression": ["responsecompression", "response compression", "响应压缩"],
        "Problem Details": ["problemdetails", "problem details", "problem details"],
        "TypedResults": ["typedresults", "typed results", "typed results"],
        "gRPC JSON": ["grpcjson", "grpc json", "grpc json", "grpc json transcoding"],
        "HTTP3": ["http3", "http 3", "http三", "h t t p 3"],

        # ── 安全 ──
        "IdentityServer": ["identityserver", "identity server", "identity server", "identity server4", "ids4"],
        "Duende": ["duende", "d u e n d e", "端嘚", "duende"],
        "OIDC": ["oidc", "o i d c", "openid connect", "o i d c"],
        "Data Protection": ["dataprotection", "data protection", "数据保护"],
        "Anti-forgery": ["antiforgery", "anti forgery", "anti forgery", "防伪token", "防跨站"],
        "SameSite": ["samesite", "same site", "same site"],
        "HSTS": ["hsts", "h s t s", "hsts"],
        "CSP": ["csp", "c s p", "csp", "内容安全策略"],

        # ── 架构 / 模式 ──
        "Clean Architecture": ["cleanarchitecture", "clean architecture", "clean architecture", "干净架构"],
        "垂直切片": ["垂直切片", "vertical slice", "垂直切面"],
        "Result模式": ["result模式", "result pattern", "瑞早pattern", "结果模式"],
        "Outbox": ["outbox", "out box", "out box", "发件箱模式"],
        "Idempotency": ["idempotency", "idem potency", "爱等potency", "幂等"],
        "Saga": ["saga", "s a g a", "萨嘎", "saga"],
        "Compensating Transaction": ["compensatingtransaction", "compensating transaction", "补偿事务"],
        "Unit of Work": ["unitofwork", "unit of work", "unit of work", "工作单元"],
        "Repository模式": ["repository模式", "repository pattern", "瑞剖色特瑞模式"],

        # ── 数据库驱动 ──
        "Npgsql": ["npgsql", "n p g s q l", "npg sql", "en pg sql", "npgsql"],
        "MySqlConnector": ["mysqlconnector", "mysql connector", "mysql connector", "mysql康奈克特"],
        "StackExchange.Redis": ["stackexchangeredis", "stackexchange redis", "stack exchange redis"],
        "MongoDB Driver": ["mongodbdriver", "mongodb driver", "mongo driver"],
        "Marten": ["marten", "m a r t e n", "马腾", "marten", "marten db"],
        "SQLKata": ["sqlkata", "sql kata", "sql kata", "sqlkata"],

        # ── 消息 / 事件总线 ──
        "MassTransit": ["masstransit", "mass transit", "mass transit", "马斯川sit"],
        "NServiceBus": ["nservicebus", "n service bus", "n service bus"],
        "Rebus": ["rebus", "r e b u s", "瑞巴斯", "rebus"],
        "Wolverine": ["wolverine", "wol ver ine", "沃尔福瑞", "wolverine"],
        "Brighter": ["brighter", "brigh ter", "布莱特", "brighter"],

        # ── 测试 / 质量 ──
        "TestContainers": ["testcontainers", "test containers", "test containers", "测试容器"],
        "Playwright.NET": ["playwrightdotnet", "playwright dotnet", "playwright点net"],
        "WebApplicationFactory": ["webapplicationfactory", "web application factory", "web app factory"],
        "SpecFlow": ["specflow", "spec flow", "spec flow", "specflow", "speck flow", "BDD框架"],
        "Verify": ["verify", "v e r i f y", "verify", "verify snapshot"],
        "Snapshooter": ["snapshooter", "snap shooter", "snapshot", "快照测试"],
        "Respawn": ["respawn", "re spawn", "瑞斯pawn", "respawn"],
        "WireMock": ["wiremock", "wire mock", "wire mock", "外儿mock"],

        # ── Unity 深度 ──
        "ScriptableObject": ["scriptableobject", "scriptable object", "scriptable object", "可脚本对象"],
        "NavMesh": ["navmesh", "nav mesh", "nav mesh", "导航网格"],
        "AnimatorController": ["animatorcontroller", "animator controller", "动画控制器"],
        "DOTS": ["dots", "d o t s", "data oriented tech stack", "dots"],
        "ECS": ["ecs", "e c s", "entity component system", "e c s", "实体组件系统"],
        "IL2CPP": ["il2cpp", "i l 2 c p p", "il2cpp", "i l to cpp"],
        "Burst Compiler": ["burstcompiler", "burst compiler", "burst compiler", "波斯特编译"],
        "Job System": ["jobsystem", "job system", "job system", "job系统"],
        "Addressables": ["addressables", "ad dress ables", "addressable", "可寻址资源"],
        "Raycast": ["raycast", "ray cast", "ray cast", "射线cast"],
        "Lerp": ["lerp", "l e r p", "线性插值", "lerp"],
        "Slerp": ["slerp", "s l e r p", "球面插值", "slerp"],
        "Quaternion": ["quaternion", "qua ter nion", "四元数", "夸特腻恩"],
        "Rigidbody": ["rigidbody", "rigid body", "rigidbody", "缸体"],
        "Collider": ["collider", "col lider", "碰撞体", "克来得"],
        "LOD": ["lod", "l o d", "level of detail", "lod"],
        "Occlusion Culling": ["occlusionculling", "occlusion culling", "遮挡剔除", "阿科路真卡令"],
        "Texture Atlas": ["textureatlas", "texture atlas", "texture atlas", "贴图图集"],
        "Shader Graph": ["shadergraph", "shader graph", "shader graph", "谁的graph"],
        "VFX Graph": ["vfxgraph", "vfx graph", "vfx graph"],
        "Timeline": ["timeline", "time line", "time line", "太姆莱恩"],
        "Cinemachine": ["cinemachine", "cine machine", "cine machine", "影机"],

        # ── 现代 .NET / 语言特性 ──
        "Source Generator": ["sourcegenerator", "source generator", "source generator", "源码生成器"],
        "Keyed DI": ["keyeddi", "keyed di", "keyed dependency injection", "键控DI"],
        "Interface": ["interface", "inter face", "interface", "因特face", "接口"],
        "Abstract Class": ["abstractclass", "abstract class", "abstract class", "抽象类"],
        "Generic Host": ["generichost", "generic host", "generic host", "通用主机"],
        "IHostedService": ["ihostedservice", "i hosted service", "i hosted service"],
        "BackgroundService": ["backgroundservice", "background service", "后台service"],
        "Channel": ["channel", "chan nel", "channel", "channel"],
        "Top-level Statements": ["toplevelstatements", "top level statements", "顶级语句"],
        "Global Usings": ["globalusings", "global usings", "全局using", "global using"],
        "File-scoped Namespace": ["filescopednamespace", "file scoped namespace", "文件作用域namespace"],
        "Init Accessor": ["initaccessor", "init accessor", "init accessor", "init"],
        "Required Members": ["requiredmembers", "required members", "必填成员"],
        "Primary Constructor": ["primaryconstructor", "primary constructor", "主构造函数"],
        "Collection Expression": ["collectionexpression", "collection expression", "集合表达式"],
        "Raw String": ["rawstring", "raw string", "raw string", "原始字符串"],
        "UTF-8 String": ["utf8string", "utf8 string", "utf 8 string", "utf8"],
        "Regex Source Gen": ["regexsourcegen", "regex source gen", "正则source gen"],

        # ── Azure 补充 ──
        "Durable Functions": ["durablefunctions", "durable functions", "持久函数"],
        "Isolated Process": ["isolatedprocess", "isolated process", "隔离进程"],
        "Service Bus Topic": ["servicebustopic", "service bus topic", "service bus topic"],
        "Cosmos DB Change Feed": ["cosmoschangefeed", "cosmos change feed", "cosmos change feed"],
        "SignalR Service": ["signalrservice", "signalr service", "signal r service"],
        "Key Vault": ["keyvault", "key vault", "key vault", "密钥保管库"],
        "Managed Identity": ["managedidentity", "managed identity", "managed identity", "托管标识"],
        "Application Gateway": ["applicationgateway", "application gateway", "应用网关"],
        "Front Door": ["frontdoor", "front door", "front door", "前门"],

        # ── .NET 社区工具 ──
        "Carter": ["carter", "c a r t e r", "卡特", "carter", "carter"],
        "FastEndpoints": ["fastendpoints", "fast endpoints", "fast endpoints", "快速endpoint"],
        "BenchmarkDotNet": ["benchmarkdotnet", "benchmark dotnet", "benchmark dot net"],
        "Polly": ["polly", "p o l l y", "珀利", "polly", "polly"],
        "Humanizer": ["humanizer", "hu man izer", "humanizer", "友好化"],
        "MoreLinq": ["morelinq", "more linq", "more linq", "更多linq"],
        "CsvHelper": ["csvhelper", "csv helper", "csv helper"],
        "HtmlAgilityPack": ["htmlagilitypack", "html agility pack", "html pack"],
        "PuppeteerSharp": ["puppeteersharp", "puppeteer sharp", "puppeteer下普"],
        "ImageSharp": ["imagesharp", "image sharp", "image sharp"],
    },
}
