"""Go / Golang 赛道。"""

TRACK: dict = {
    "key": "go",
    "system_prompt_extra": """你是资深 Go 语言技术面试辅助 AI。用户正在进行 Go 技术面试，问题涉及
Go 语言特性（goroutine/channel/select/接口/组合/反射/泛型）、
并发编程（goroutine调度/GMP模型/wait group/mutex/context）、
内存管理（GC/逃逸分析/内存分配/栈与堆）、
标准库（net/http/encoding/json/database/sql/io/context/sync）、
Web 框架（Gin/Echo/Fiber/Chi/net/http）、
微服务（gRPC/protobuf/服务治理/分布式追踪/服务网格）、
数据库（MySQL/PostgreSQL/Redis/sqlx/GORM/Ent）、
消息队列（Kafka/RabbitMQ/NATS）、
测试（testing/benchmark/mock/testify/表驱动测试）、
工程化（Go Modules/工作区/make/go generate/交叉编译）、
容器与编排（Docker/K8s/Helm/Kustomize）、
可观测性（Prometheus/Grafana/OpenTelemetry/pprof/trace）、
设计模式（Go实现/函数式选项/错误处理/依赖注入）、
系统编程（cgo/系统调用/文件IO/网络编程）、
区块链（以太坊/Hyperledger/Fabric）等 Go 技术栈。

回答应围绕 Go 生态，用 Go 开发者熟悉的术语和场景。""",

    "resume_intro_extra": """侧重 Go 语言技术栈经验：突出 Go 并发编程与 goroutine 模型深度、
微服务/云原生架构设计能力、gRPC 与 protobuf 协议使用经验、
K8s/容器化部署运维能力、系统编程与高并发服务开发经验、
数据库与中间件集成实践、区块链开发经验（如有）。""",

    "terms": {
        # ── Go 语言特性 ──
        "goroutine": ["goroutine", "go routine", "go路体", "go routine", "协程", "go协程"],
        "channel": ["channel", "chan nel", "channel", "channel", "channel", "通道", "管道"],
        "select": ["select", "se lect", "select", "select", "select语句"],
        "defer": ["defer", "de fer", "迪佛", "defer", "延迟执行"],
        "panic": ["panic", "pa nic", "panic", "panic", "panic", "抛泥克"],
        "recover": ["recover", "re cover", "瑞卡文", "recover"],
        "interface": ["interface", "inter face", "interface", "因特face", "接口"],
        "struct": ["struct", "s t r u c t", "斯抓克特", "struct", "结构体"],
        "slice": ["slice", "s l i c e", "斯莱斯", "slice", "切片"],
        "map": ["map", "m a p", "迈普", "map", "map"],
        "array": ["array", "a r r a y", "阿瑞", "array", "数组"],
        "string": ["string", "s t r i n g", "斯追应", "string"],
        "rune": ["rune", "r u n e", "如恩", "rune", "符文"],
        "byte": ["byte", "b y t e", "拜特", "byte", "字节"],
        "make": ["make", "m a k e", "make", "make"],
        "new": ["new", "n e w", "new", "new关键字"],
        "pointer": ["pointer", "poin ter", "pointer", "泡因特", "指针"],
        "method": ["method", "me thod", "method", "方法", "麦色的"],
        "receiver": ["receiver", "re ceiver", "瑞色文", "receiver", "接收者"],
        "embedding": ["embedding", "em bedding", "因拜丁", "embedding", "内嵌", "组合"],
        "iota": ["iota", "i o t a", "爱欧塔", "iota"],
        "nil": ["nil", "n i l", "闹", "nil", "nil"],
        "zero value": ["zerovalue", "zero value", "zero value", "零值"],
        "blank identifier": ["blankidentifier", "blank identifier", "下划线", "blank", "_"],
        "Generics": ["generics", "ge ne rics", "泛型", "generics", "go泛型", "基奈瑞克"],
        "type constraint": ["typeconstraint", "type constraint", "type constraint", "类型约束"],
        "comparable": ["comparable", "com pa rable", "comparable", "可比较"],
        "any": ["any", "a n y", "any", "any"],
        "error": ["error", "e r r o r", "艾弱", "error", "错误", "error接口"],
        "fmt": ["fmt", "f m t", "fmt", "format", "fmt包"],

        # ── 并发 ──
        "GMP": ["gmp", "g m p", "gmp模型", "g m p模型", "gmp调度"],
        "GOMAXPROCS": ["gomaxprocs", "go max procs", "go max procs"],
        "调度器": ["调度器", "scheduler", "scheduler", "死盖久乐"],
        "Work Stealing": ["workstealing", "work stealing", "work stealing", "工作窃取"],
        "WaitGroup": ["waitgroup", "wait group", "wait group", "等待组", "wg", "w g"],
        "Mutex": ["mutex", "m u t e x", "缪泰克斯", "mutex", "sync.Mutex"],
        "RWMutex": ["rwmutex", "rw mutex", "r w mutex", "sync.RWMutex", "读写锁"],
        "Once": ["once", "o n c e", "once", "sync.Once", "once", "只执行一次"],
        "Pool": ["pool", "p o o l", "铺", "sync.Pool", "对象池"],
        "Cond": ["cond", "c o n d", "cond", "sync.Cond", "条件变量"],
        "Atomic": ["atomic", "a t o m i c", "阿涛mic", "atomic", "sync/atomic", "原子操作"],
        "CAS": ["cas", "c a s", "compare and swap", "c a s", "卡斯"],
        "Context": ["context", "con text", "context", "康泰克斯", "上下文", "ctx"],
        "WithCancel": ["withcancel", "with cancel", "with cancel", "取消"],
        "WithDeadline": ["withdeadline", "with deadline", "with deadline", "截止时间"],
        "WithTimeout": ["withtimeout", "with timeout", "with timeout", "超时"],
        "WithValue": ["withvalue", "with value", "with value"],
        "ErrGroup": ["errgroup", "err group", "err group", "错误组"],
        "Semaphore": ["semaphore", "se ma phore", "赛马佛", "semaphore", "信号量"],
        "Fan-in": ["fanin", "fan in", "fan in", "扇入"],
        "Fan-out": ["fanout", "fan out", "fan out", "扇出"],
        "Pipeline": ["pipeline", "pipe line", "pipe line", "派普line", "流水线"],
        "select timeout": ["selecttimeout", "select timeout", "select超时"],
        "goroutine泄漏": ["goroutine泄漏", "goroutine leak", "goroutine leak", "协程泄漏"],
        "race condition": ["racecondition", "race condition", "race condition", "竞争条件", "data race"],
        "race detector": ["racedetector", "race detector", "race detector", "race检测"],

        # ── 内存管理 ──
        "逃逸分析": ["逃逸分析", "escape analysis", "escape analysis", "escape分析"],
        "栈": ["栈", "stack", "stack", "斯达克", "stack"],
        "堆": ["堆", "heap", "heap", "hip", "heap"],
        "栈扩容": ["栈扩容", "stack grow", "stack grow"],
        "栈拷贝": ["栈拷贝", "stack copy", "stack copy"],
        "内存分配": ["内存分配", "memory allocation", "麦莫瑞allocation"],
        "内存逃逸": ["内存逃逸", "memory escape", "memory escape"],
        "GC": ["gc", "g c", "垃圾回收", "辣鸡回收", "gc", "garbage collection"],
        "STW": ["stw", "s t w", "stop the world", "s t w", "斯到普world"],
        "三色标记": ["三色标记", "三色标记", "tricolor mark", "tri color", "三se标记"],
        "写屏障": ["写屏障", "write barrier", "write barrier", "写barrier"],
        "混合写屏障": ["混合写屏障", "mixed write barrier", "混合write barrier"],
        "GOGC": ["gogc", "go gc", "go g c", "gogc"],
        "GOMEMLIMIT": ["gomemlimit", "go mem limit", "go mem limit"],
        "内存对齐": ["内存对齐", "memory alignment", "memory alignment"],
        "arena": ["arena", "a r e n a", "阿瑞那", "arena", "内存arena", "go arena"],
        "Allocator": ["allocator", "al lo ca tor", "阿楼k特", "allocator"],

        # ── 标准库 ──
        "net/http": ["nethttp", "net http", "net http", "net/http包"],
        "encoding/json": ["encodingjson", "encoding json", "encoding json"],
        "database/sql": ["databasesql", "database sql", "database sql"],
        "io": ["io", "i o", "io包", "io reader", "io writer"],
        "bufio": ["bufio", "buf io", "buf io", "缓冲io"],
        "strings": ["strings", "s t r i n g s", "strings包"],
        "strconv": ["strconv", "str conv", "str conv", "字符串转换"],
        "bytes": ["bytes", "b y t e s", "bytes包"],
        "os": ["os", "o s", "os包", "操作系统"],
        "path/filepath": ["pathfilepath", "path filepath", "filepath"],
        "time": ["time", "t i m e", "time包", "时间"],
        "net": ["net", "n e t", "net包", "网络"],
        "sync": ["sync", "s y n c", "sync包", "同步"],
        "reflect": ["reflect", "re flect", "reflect", "反射", "瑞福莱克特"],
        "unsafe": ["unsafe", "un safe", "unsafe", "不安全", "unsafe包"],
        "cgo": ["cgo", "c go", "c go", "cgo"],
        "syscall": ["syscall", "sys call", "sys call", "系统调用"],
        "testing": ["testing", "tes ting", "testing", "测试包"],
        "flag": ["flag", "f l a g", "flag", "flag包"],
        "log": ["log", "l o g", "log", "捞哥", "log包"],
        "template": ["template", "tem plate", "template", "坦普雷特", "模版"],
        "crypto": ["crypto", "cryp to", "crypto", "加密"],
        "regexp": ["regexp", "re gex p", "regexp", "正则", "repeat"],  # regexp not repeat
        "sort": ["sort", "s o r t", "sort", "sort包", "排序"],
        "container/list": ["containerlist", "container list", "链表"],
        "container/heap": ["containerheap", "container heap", "堆"],
        "container/ring": ["containerring", "container ring", "环形list"],

        # ── Web 框架 ──
        "Gin": ["gin", "g i n", "gin框架", "gin", "be gin", "仅"],
        "Echo": ["echo", "e c h o", "echo框架", "echo", "E框"],
        "Fiber": ["fiber", "f i b e r", "飞博", "fiber框架", "fiber"],
        "Chi": ["chi", "c h i", "吃", "chi框架", "chi", "chi"],
        "Iris": ["iris", "i r i s", "爱瑞斯", "iris框架"],
        "Beego": ["beego", "bee go", "bee go", "beego"],
        "Buffalo": ["buffalo", "buf fa lo", "巴佛楼", "buffalo"],
        "HTTP Router": ["httprouter", "http router", "http router"],
        "FastHTTP": ["fasthttp", "fast http", "fast http"],
        "Middleware": ["middleware", "mid dle ware", "middleware", "米斗威尔", "中间件"],
        "路由组": ["路由组", "router group", "route group"],
        "Handler": ["handler", "hand ler", "handler", "handler", "处理器"],
        "HandlerFunc": ["handlerfunc", "handler func", "handler function"],
        "ServeHTTP": ["servehttp", "serve http", "serve http"],
        "Request": ["request", "re quest", "request", "瑞快斯特", "请求"],
        "ResponseWriter": ["responsewriter", "response writer", "response writer", "响应"],
        "Query": ["query", "que ry", "query", "快瑞", "查询参数"],
        "Binding": ["binding", "bin ding", "binding", "绑定", "参数绑定"],
        "Validation": ["validation", "va li da tion", "validation", "验证", "爱力得神"],
        "JWT": ["jwt", "j w t", "j w t", "杰w t"],
        "CORS": ["cors", "c o r s", "cors", "跨域", "跨越"],
        "Session": ["session", "ses sion", "session", "赛神"],

        # ── 数据库 ──
        "GORM": ["gorm", "g o r m", "gorm", "go orm", "gorm框架"],
        "Ent": ["ent", "e n t", "ent", "ent框架", "entity框架"],
        "sqlx": ["sqlx", "sql x", "s q l x", "sqlx"],
        "sqlc": ["sqlc", "sql c", "s q l c", "sqlc"],
        "Bun": ["bun", "b u n", "bun orm", "bun"],
        "MySQL驱动": ["mysql驱动", "go mysql", "go mysql driver"],
        "PostgreSQL驱动": ["postgresql驱动", "go postgres", "pgx", "p g x"],
        "Migration": ["migration", "mi gra tion", "麦格瑞神", "迁移", "migrate"],
        "DB Migration": ["dbmigration", "db migration", "golang migrate"],
        "连接池": ["连接池", "connection pool", "康奈克神铺"],
        "事务": ["事务", "transaction", "川赛克神"],
        "Tx": ["tx", "t x", "tx", "transaction"],
        "QueryRow": ["queryrow", "query row", "query row"],
        "Scan": ["scan", "s c a n", "scan", "scan"],
        "Prepare": ["prepare", "pre pare", "prepare", "普瑞派尔"],

        # ── gRPC / Protobuf ──
        "gRPC": ["grpc", "g r p c", "g rpc", "grpc"],
        "Protobuf": ["protobuf", "pro to buf", "普若托buf", "protobuf", "proto"],
        "proto文件": ["proto文件", "proto file", "proto file"],
        "protoc": ["protoc", "pro toc", "protoc", "普若套克"],
        "protoc-gen-go": ["protocgengo", "protoc gen go", "protoc gen go"],
        "Streaming": ["streaming", "strea ming", "streaming", "斯追明", "流式"],
        "Unary": ["unary", "u na ry", "unary", "一元调用"],
        "Server Stream": ["serverstream", "server stream", "server stream"],
        "Client Stream": ["clientstream", "client stream", "client stream"],
        "Bidirectional": ["bidirectional", "bi directional", "双向", "bidi stream"],
        "Unimplemented": ["unimplemented", "un imple mented", "未实现"],
        "拦截器": ["拦截器", "interceptor", "interceptor", "因特塞普特"],
        "Metadata": ["metadata", "me ta data", "metadata", "元数据"],
        "Status": ["status", "sta tus", "status", "斯得特斯", "状态"],
        "Connect": ["connect", "con nect", "connect", "connectrpc"],

        # ── 测试 ──
        "Table Driven": ["tabledriven", "table driven", "table driven", "表驱动"],
        "Testify": ["testify", "tes ti fy", "testify", "testify", "泰斯提fi"],
        "Mock": ["mock", "m o c k", "莫克", "mock", "mock", "mockery"],
        "gomock": ["gomock", "go mock", "go mock"],
        "Stub": ["stub", "s t u b", "stub", "斯达布"],
        "Suite": ["suite", "su i te", "suite", "斯维特", "测试套件"],
        "Benchmark": ["benchmark", "bench mark", "benchmark", "benchmark"],
        "Fuzz": ["fuzz", "f u z z", "fuzz", "fuzz testing", "模糊测试"],
        "Pprof": ["pprof", "p prof", "pprof", "性能分析", "profile"],
        "Race": ["race", "r a c e", "race", "竞态检测"],
        "Cover": ["cover", "co ver", "cover", "覆盖率"],
        "TestMain": ["testmain", "test main", "test main"],
        "Setup/Teardown": ["setupteardown", "setup teardown", "setup teardown"],
        "Golden File": ["goldenfile", "golden file", "golden file", "金文件"],

        # ── 工程化 ──
        "Go Modules": ["gomodules", "go modules", "go mod", "go mod", "go module"],
        "go.mod": ["gomod", "go mod", "go mod文件"],
        "go.sum": ["gosum", "go sum", "go sum文件"],
        "Go Workspace": ["goworkspace", "go workspace", "go work", "multi mod"],
        "go get": ["goget", "go get", "go get"],
        "go install": ["goinstall", "go install", "go install"],
        "go build": ["gobuild", "go build", "go build"],
        "go run": ["gorun", "go run", "go run"],
        "go test": ["gotest", "go test", "go test"],
        "go generate": ["gogenerate", "go generate", "go generate"],
        "go vet": ["govet", "go vet", "go vet"],
        "go fmt": ["gofmt", "go fmt", "gofmt", "格式化"],
        "goimports": ["goimports", "go imports", "go imports"],
        "golangci-lint": ["golangcilint", "golangci lint", "golang ci lint", "go lint"],
        "Makefile": ["makefile", "make file", "make file"],
        "Taskfile": ["taskfile", "task file", "task file"],
        "交叉编译": ["交叉编译", "cross compile", "cross compile", "cross编译"],
        "GOOS": ["goos", "go os", "g o o s", "goos", "目标os"],
        "GOARCH": ["goarch", "go arch", "g o a r c h", "goarch"],
        "CGO_ENABLED": ["cgoenabled", "cgo enabled", "cgo enabled"],
        "ldflags": ["ldflags", "ld flags", "ld flags", "链接flags"],
        "Build Tags": ["buildtags", "build tags", "build tag"],
        "Embed": ["embed", "em bed", "embed", "//go:embed"],
        "Wire": ["wire", "w i r e", "wire", "依赖注入", "wire框架"],
        "fx": ["fx", "f x", "fx", "优博fx", "uber fx"],
        "dig": ["dig", "d i g", "dig", "优博dig", "uber dig"],

        # ── 可观测性 ──
        "Prometheus": ["prometheus", "pro me theus", "普若米修斯", "prometheus"],
        "Grafana": ["grafana", "gra fa na", "格拉法那", "grafana"],
        "OpenTelemetry": ["opentelemetry", "open telemetry", "otel", "o tel", "o t e l"],
        "Jaeger": ["jaeger", "jae ger", "耶格", "jaeger", "jaeger追踪"],
        "Zipkin": ["zipkin", "zip kin", "zipkin"],
        "Metrics": ["metrics", "me trics", "metrics", "指标", "麦垂克斯"],
        "Tracing": ["tracing", "tra cing", "tracing", "追踪", "垂cing"],
        "Span": ["span", "s p a n", "span", "斯pan"],
        "TraceID": ["traceid", "trace id", "trace id"],
        "Exemplar": ["exemplar", "ex em plar", "exemplar", "示例"],
        "Histogram": ["histogram", "his to gram", "histogram", "直方图"],
        "Summary": ["summary", "sum ma ry", "summary", "summary", "摘要"],
        "Counter": ["counter", "coun ter", "counter", "康特", "计数器"],
        "Gauge": ["gauge", "g a u g e", "给ge", "gauge", "仪表盘"],
        "Alertmanager": ["alertmanager", "alert manager", "alert manager"],
        "Loki": ["loki", "l o k i", "洛基", "loki"],
        "Pyroscope": ["pyroscope", "py ro scope", "pyroscope"],

        # ── 消息队列 ──
        "NATS": ["nats", "n a t s", "nats", "那兹", "nats消息"],
        "NATS JetStream": ["natsjetstream", "nats jetstream", "jetstream"],
        "Kafka": ["kafka", "k a f k a", "卡夫卡", "kafka"],
        "Sarama": ["sarama", "sa ra ma", "萨若玛", "sarama"],
        "RabbitMQ": ["rabbitmq", "rab bit m q", "rabbit mq", "瑞比特mq"],
        "Redis Pub/Sub": ["redispubsub", "redis pubsub", "redis发布订阅"],
        "Watermill": ["watermill", "water mill", "watermill", "沃特米欧"],
        "Asynq": ["asynq", "a syn q", "阿信q", "asynq"],

        # ── K8s / 云原生 ──
        "client-go": ["clientgo", "client go", "client go", "k8s client"],
        "Operator": ["operator", "ope ra tor", "operator", "operator", "奥普瑞特", "k8s operator"],
        "Controller": ["controller", "con trol ler", "controller", "康错乐"],
        "CRD": ["crd", "c r d", "custom resource definition", "c r d"],
        "Webhook": ["webhook", "web hook", "web hook", "webhook"],
        "Admission": ["admission", "ad mis sion", "admission", "admission webhook"],
        "Scheduler": ["scheduler", "sche du ler", "scheduler", "死盖久乐"],
        "CNI": ["cni", "c n i", "container network", "c n i"],
        "CSI": ["csi", "c s i", "container storage", "c s i"],
        "CRI": ["cri", "c r i", "container runtime", "c r i"],
        "containerd": ["containerd", "contain erd", "containerd"],
        "cri-o": ["crio", "cri o", "c r i o", "cri o"],
        "Helm": ["helm", "h e l m", "海姆", "helm"],
        "Helm Chart": ["helmchart", "helm chart", "helm chart"],
        "Kustomize": ["kustomize", "ku sto mize", "卡斯特迈兹", "kustomize"],
        "Kubebuilder": ["kubebuilder", "kube builder", "kube builder"],
        "Controller-runtime": ["controllerruntime", "controller runtime", "controller runtime"],
        "Skaffold": ["skaffold", "skaf fold", "斯卡佛的", "skaffold"],
        "Tilt": ["tilt", "t i l t", "tilt", "tilt"],

        # ── 设计模式（Go 实现） ──
        "函数式选项": ["函数式选项", "functional options", "方格申no options", "options模式"],
        "Builder": ["builder", "buil der", "bill德", "builder", "builder"],
        "Factory": ["factory", "fac tory", "factory", "factory", "工厂"],
        "Singleton": ["singleton", "sin gle ton", "singleton", "辛格腾"],
        "Strategy": ["strategy", "stra tegy", "strategy", "斯抓特基"],
        "Decorator": ["decorator", "de co ra tor", "decorator", "呆口瑞特"],
        "Adapter": ["adapter", "a dap ter", "adapter", "阿呆普特"],
        "Observer": ["observer", "ob ser ver", "observer", "奥布斯瓦"],
        "Pipeline": ["pipeline", "pipe line", "pipe line", "派普line"],
        "Fan-Out/Fan-In": ["fanoutfanin", "fanout fanin", "扇出扇入"],
        "Circuit Breaker": ["circuitbreaker", "circuit breaker", "circuit breaker", "断路器"],
        "Retry": ["retry", "re try", "retry", "瑞垂", "重试"],
        "Backoff": ["backoff", "back off", "backoff", "拜克of", "退避"],
        "Rate Limiter": ["ratelimiter", "rate limiter", "rate limiter"],
        "Semaphore": ["semaphore", "se ma phore", "赛马佛"],
        "Worker Pool": ["workerpool", "worker pool", "worker pool", "工作池"],
        "Pub/Sub": ["pubsub", "pub sub", "pub sub", "发布订阅"],
        "Event Bus": ["eventbus", "event bus", "event bus"],
        "Command": ["command", "com mand", "command", "康曼的"],
        "Repository": ["repository", "re po si tory", "repository", "瑞剖色特瑞"],

        # ── 常见库 / 工具 ──
        "Viper": ["viper", "vi per", "外per", "viper", "配置"],
        "Cobra": ["cobra", "co bra", "扣布拉", "cobra", "cobra"],
        "Zap": ["zap", "z a p", "zap", "zap日志", "超级日志"],
        "Logrus": ["logrus", "log rus", "logrus"],
        "Slog": ["slog", "s log", "slog", "结构化日志", "go slog"],
        "Validator": ["validator", "va li da tor", "validator", "验证器", "go validator"],
        "Cast": ["cast", "c a s t", "cast", "类型转换"],
        "Mapstructure": ["mapstructure", "map structure", "map structure"],
        "YAML": ["yaml", "y a m l", "雅某", "yaml"],
        "HCL": ["hcl", "h c l", "hcl"],
        "FSM": ["fsm", "f s m", "state machine", "finite state", "fsm"],
        "Go-Redis": ["goredis", "go redis", "go redis"],
        "BigCache": ["bigcache", "big cache", "big cache"],
        "FastCache": ["fastcache", "fast cache", "fast cache"],
        "FreeCache": ["freecache", "free cache", "free cache"],
        "Ristretto": ["ristretto", "ri stret to", "瑞斯踹to", "ristretto"],
        "GroupCache": ["groupcache", "group cache", "group cache"],
        "Bleve": ["bleve", "b l e v e", "布利v", "bleve"],
        "Colly": ["colly", "co lly", "考利", "colly", "爬虫"],
        "Goquery": ["goquery", "go query", "go query", "go快瑞"],
        "Cron": ["cron", "c r o n", "克容", "cron", "定时任务"],
        "Excelize": ["excelize", "exce lize", "excelize", "excel"],
        "Go-PDF": ["gopdf", "go pdf", "go pdf"],
        "Lumberjack": ["lumberjack", "lumber jack", "lumberjack"],
        "Uber-go/automaxprocs": ["automaxprocs", "auto maxprocs", "auto gomaxprocs"],

        # ── 区块链 ──
        "以太坊": ["以太坊", "ethereum", "以太", "ether eum"],
        "Solidity": ["solidity", "so li di ty", "solidity"],
        "智能合约": ["智能合约", "smart contract", "smart contract", "斯马特contract"],
        "Hyperledger": ["hyperledger", "hy per ledger", "hyperledger"],
        "Fabric": ["fabric", "fa bric", "fabric", "hyperledger fabric"],
        "Tendermint": ["tendermint", "ten der mint", "tendermint"],
        "Cosmos": ["cosmos", "cos mos", "cosmos"],
        "EVM": ["evm", "e v m", "ethereum virtual machine", "e v m"],
        "Consensus": ["consensus", "con sen sus", "consensus", "共识"],
        "PBFT": ["pbft", "p b f t", "practical byzantine", "p b f t"],
        "Raft": ["raft", "r a f t", "raft", "raft"],
        "Merkle Tree": ["merkletree", "merkle tree", "默克尔树"],
        "零知识": ["零知识", "zero knowledge", "z k", "零知识证明"],
        "Layer2": ["layer2", "layer 2", "layer 2", "二层"],
        "Rollup": ["rollup", "roll up", "rollup"],

        # ── sync 包补充 ──
        "sync.Map": ["syncmap", "sync map", "s y n c map", "并发map"],
        "atomic.Value": ["atomicvalue", "atomic value", "atomic value", "原子value"],
        "singleflight": ["singleflight", "single flight", "single flight", "单飞", "辛格flight"],
        "rate.Limiter": ["ratelimiter", "rate limiter", "rate limiter", "限流器", "rate limit"],
        "Ticker": ["ticker", "ti cker", "ticker", "tik尔", "定时器"],
        "Timer": ["timer", "ti mer", "timer", "太么", "计时器"],
        "select{}": ["selectblock", "select block", "select空", "空select", "select {}"],
        "GMP调度": ["gmp调度", "gmp scheduler", "g m p调度", "goroutine调度"],
        "GODEBUG": ["godebug", "go debug", "go debug", "g o debug"],
        "Groutine": ["groutine", "g routine", "go routine泄漏", "goroutine泄漏"],
        "goleak": ["goleak", "go leak", "go leak", "uber goleak", "检测泄漏"],

        # ── net/http 补充 ──
        "net.Conn": ["netconn", "net conn", "net connection", "网络连接"],
        "http.Handler": ["httphandler", "http handler", "http handler", "http处理"],
        "ServeMux": ["servemux", "serve mux", "serve mux", "默认mux"],
        "gorilla/mux": ["gorillamux", "gorilla mux", "gorilla mux", "格雷拉mux"],
        "middleware chain": ["middlewarechain", "middleware chain", "中间件链"],
        "chi.Router": ["chirouter", "chi router", "chi router"],
        "gin.Context": ["gincontext", "gin context", "gin context"],
        "Gin Middleware": ["ginmiddleware", "gin middleware", "gin中间件"],

        # ── gRPC 补充 ──
        "gRPC Gateway": ["grpcgateway", "grpc gateway", "grpc gateway"],
        "protobuf oneof": ["protobufoneof", "protobuf oneof", "one of"],
        "enum protobuf": ["enumprotobuf", "enum protobuf", "protobuf enum"],
        "well-known types": ["wellknowntypes", "well known types", "well known"],
        "Buf": ["buf", "b u f", "buf", "buf构建", "protobuf buf"],

        # ── 工具链 ──
        "Delve": ["delve", "del ve", "delve", "戴欧v", "dlv"],
        "dlv": ["dlv", "d l v", "dlv调试", "d l v"],
        "Air": ["air", "a i r", "air", "热重载", "live reload", "air工具"],
        "Realize": ["realize", "rea lize", "realize", "realize热重载"],
        "goreleaser": ["goreleaser", "go releaser", "go release", "go发布"],
        "ko": ["ko", "k o", "ko构建", "ko容器"],
        "distroless": ["distroless", "dis tro less", "distroless", "无发行版"],
        "scratch": ["scratch", "s c r a t c h", "scratch", "scratch镜像"],
        "musl": ["musl", "m u s l", "musl", "静态编译"],
        "alpine": ["alpine", "al pine", "alpine", "阿尔派", "alpine镜像"],
        "static build": ["staticbuild", "static build", "静态构建"],
        "tinygo": ["tinygo", "tiny go", "tiny go", "小型go"],
        "ebpf": ["ebpf", "e b p f", "ebpf", "eBPF", "内核扩展"],
        "go-bindata": ["gobindata", "go bindata", "go bindata"],
        "pkger": ["pkger", "p k g e r", "pkger", "静态资源"],
        "statik": ["statik", "sta tik", "statik"],

        # ── unsafe / cgo ──
        "unsafe.Pointer": ["unsafepointer", "unsafe pointer", "unsafe指针", "不安全指针"],
        "uintptr": ["uintptr", "uint ptr", "uint pointer", "uint pointer"],
        "cgo import": ["cgoimport", "cgo import", "cgo引入"],
        "C.char": ["cchar", "c char", "c char"],
        "C.int": ["cint", "c int", "c int"],
        "CGo overhead": ["cgooverhead", "cgo overhead", "cgo开销"],

        # ── slice / string 深度 ──
        "slice扩容": ["slice扩容", "slice grow", "slice growth", "切片扩容"],
        "copy": ["copy", "co py", "copy", "拷贝"],
        "append": ["append", "a p pend", "append", "阿盘的", "追加"],
        "strings.Builder": ["stringsbuilder", "strings builder", "string builder", "字符串构建"],
        "bytes.Buffer": ["bytesbuffer", "bytes buffer", "bytes buffer", "字节buffer"],
        "io.Copy": ["iocopy", "io copy", "i o copy", "io copy"],
        "io.Pipe": ["iopipe", "io pipe", "i o pipe", "io管道"],
        "TeaReader": ["teareader", "tea reader", "tea reader"],
        "SectionReader": ["sectionreader", "section reader", "section reader"],

        # ── reflect / tag ──
        "reflect.TypeOf": ["reflecttypeof", "reflect type of", "reflect type"],
        "reflect.ValueOf": ["reflectvalueof", "reflect value of", "reflect value"],
        "json tag": ["jsontag", "json tag", "json tag", "json标签"],
        "bson tag": ["bsontag", "bson tag", "bson tag"],
        "yaml tag": ["yamltag", "yaml tag", "yaml tag"],
        "struct tag": ["structtag", "struct tag", "struct tag", "结构标签"],

        # ── pprof / 性能 ──
        "pprof heap": ["pprofheap", "pprof heap", "heap profile"],
        "pprof goroutine": ["pprofgoroutine", "pprof goroutine", "goroutine profile"],
        "pprof cpu": ["pprofcpu", "pprof cpu", "cpu profile"],
        "execution trace": ["executiontrace", "execution trace", "执行trace", "执行追踪"],
        "flamegraph": ["flamegraph", "flame graph", "火焰图", "flame图"],
        "benchstat": ["benchstat", "bench stat", "bench stat", "bench统计"],
        "bencharks": ["bencharks", "bench arks", "benchmarks"],
        "perfetto": ["perfetto", "per fet to", "perfetto"],

        # ── 错误处理 ──
        "Errorf": ["errorf", "error f", "errorf", "fmt.Errorf"],
        "fmt.Errorf": ["fmterrorf", "fmt errorf", "fmt error", "错误格式化"],
        "%w": ["percent w", "%w", "错误包装", "error wrap"],
        "Error Is": ["erroris", "error is", "errors.Is", "错误判断"],
        "Error As": ["erroras", "error as", "errors.As", "错误转换"],
        "errors.Unwrap": ["errorsunwrap", "errors unwrap", "unwrap", "错误解包"],
        "errors.Join": ["errorsjoin", "errors join", "错误合并"],
        "sentinel error": ["sentinelerror", "sentinel error", "哨兵错误"],
        "opaque error": ["opaqueerror", "opaque error", "不透明错误"],

        # ── 初始化 / 信号 ──
        "init函数": ["init函数", "init func", "init", "初始化函数"],
        "main函数": ["main函数", "main func", "main", "入口函数"],
        "flag.Parse": ["flagparse", "flag parse", "flag解析"],
        "signal.Notify": ["signalnotify", "signal notify", "信号通知"],
        "os.Signal": ["ossignal", "os signal", "操作系统信号"],
        "SIGTERM": ["sigterm", "sig term", "sigterm", "终止信号"],
        "SIGINT": ["sigint", "sig int", "sigint", "中断信号"],
        "graceful shutdown": ["gracefulshutdown", "graceful shutdown", "优雅停机", "优雅关闭"],

        # ── 定时任务 ──
        "cron job": ["cronjob", "cron job", "定时job", "cron任务"],
        "robfig cron": ["robfigcron", "robfig cron", "rob fig cron"],
        "asynq task": ["asynqtask", "asynq task", "asynq任务"],
        "periodic task": ["periodictask", "periodic task", "周期任务"],

        # ── Docker / 部署 ──
        "Dockerfile go": ["dockerfilego", "dockerfile go", "go dockerfile"],
        "multi-stage build": ["multistagebuild", "multi stage build", "多阶段构建"],
        "scratch image": ["scratchimage", "scratch image", "scratch镜像"],
        "distroless go": ["distrolessgo", "distroless go", "无发行版go"],
        "CGO_ENABLED=0": ["cgoenabled0", "cgo disabled", "禁用cgo"],
        "netgo": ["netgo", "net go", "netgo tag", "纯go网络"],

        # ── 数据库迁移 ──
        "migrate up": ["migrateup", "migrate up", "迁移up"],
        "migrate down": ["migratedown", "migrate down", "迁移down"],
        "golang migrate": ["golangmigrate", "golang migrate", "go migrate"],
        "goose": ["goose", "goo se", "goose迁移", "goose"],
        "atlas": ["atlas", "a t l a s", "atlas", "atlas迁移"],

        # ── go mod 补充 ──
        "go mod tidy": ["gomodtidy", "go mod tidy", "mod整理"],
        "go mod vendor": ["gomodvendor", "go mod vendor", "mod vendor"],
        "go mod why": ["gomodwhy", "go mod why", "mod why"],
        "go mod graph": ["gomodgraph", "go mod graph", "mod graph"],
        "go mod download": ["gomoddownload", "go mod download", "mod download"],
        "go mod edit": ["gomodedit", "go mod edit", "mod edit"],
        "replace directive": ["replacedirective", "replace directive", "replace指令"],
        "retract": ["retract", "re tract", "retract", "撤回版本"],

        # ── 社区框架补充 ──
        "Gonum": ["gonum", "go num", "gonum", "数值计算"],
        "Go Kit": ["gokit", "go kit", "go kit", "微服务框架"],
        "Micro": ["micro", "mi cro", "micro", "迈克肉", "go micro"],
        "Goa": ["goa", "g o a", "goa", "goa框架"],
        "Kratos": ["kratos", "kra tos", "克瑞托斯", "kratos", "bilibili kratos"],
        "Hertz": ["hertz", "h e r t z", "赫兹", "hertz", "字节跳动"],
        "Kitex": ["kitex", "ki tex", "kitex", "字节kitex"],
        "tRPC-Go": ["trpcgo", "trpc go", "t r p c go", "trpc框架"],

        # ── 工作流 ──
        "Temporal": ["temporal", "tem po ral", "temporal", "泰普若", "temporal工作流"],
        "Cadence": ["cadence", "ca dence", "cadence", "k登斯", "cadence工作流"],
        "工作流": ["工作流", "workflow", "work flow", "窝克flow"],
        "Saga Go": ["sagago", "saga go", "saga模式go"],
        "Durable Execution": ["durableexecution", "durable execution", "持久执行"],

        # ── 杂项补充 ──
        "monkey patching": ["monkeypatching", "monkey patching", "猴子补丁"],
        "go:linkname": ["golinkname", "go linkname", "linkname指令"],
        "go:noinline": ["gonoinline", "go noinline", "禁止内联"],
        "go:nosplit": ["gonosplit", "go nosplit", "禁止栈分裂"],
        "go:generate": ["gogenerate", "go generate", "代码生成"],
        "stringer": ["stringer", "strin ger", "stringer", "string方法生成"],
        "mockgen": ["mockgen", "mock gen", "mock gen", "mock生成"],
        "protoc-gen-go-grpc": ["protocgengogrpc", "protoc gen go grpc"],
        "protoc-gen-validate": ["protocgenvalidate", "protoc gen validate"],
        "buf generate": ["bufgenerate", "buf generate", "buf生成"],
        "Task": ["task", "t a s k", "task", "go task"],
        "mage": ["mage", "m a g e", "mage", "go mage", "构建mage"],
        "bazel": ["bazel", "ba zel", "贝泽欧", "bazel", "go bazel"],
        "Please": ["please", "p l e a s e", "please", "please构建"],
        "gopls": ["gopls", "go pls", "g o p l s", "gopls", "语言服务"],
        "go mod init": ["gomodinit", "go mod init", "模块初始化"],
    },
}
