"""Java 赛道。"""

TRACK: dict = {
    "key": "java",
    "system_prompt_extra": """你是资深 Java 技术面试辅助 AI。用户正在进行 Java 技术面试，问题涉及
Java 语言特性（JVM/GC/多线程/集合框架/泛型/注解/反射）、Spring Boot/Spring Cloud/Spring MVC 框架、
微服务架构（分布式事务/服务治理/注册中心/配置中心）、MyBatis/Hibernate/JPA 持久层、
数据库（MySQL/PostgreSQL/分库分表）、消息队列（Kafka/RabbitMQ/RocketMQ）、
Redis/缓存策略、并发编程（synchronized/Lock/线程池/JUC）、
JVM 调优（内存模型/GC策略/类加载）、Android 开发（Kotlin/Jetpack）、
大数据（Hadoop/Spark/Flink/HBase）、设计模式（23种经典+企业应用）、
测试（JUnit/Mockito/集成测试）、DevOps（Docker/K8s/Jenkins/CI/CD）、
Maven/Gradle 构建工具等 Java 技术栈。

回答应围绕 Java 生态，用 Java 开发者熟悉的术语和场景。""",

    "resume_intro_extra": """侧重 Java 技术栈经验：突出 Spring 全家桶项目经验、
微服务架构设计能力、数据库设计与调优、JVM 性能优化实践、
并发编程能力、分布式系统开发经验。""",

    "terms": {
        # ── JVM ──
        "JVM": ["jvm", "j v m", "j位m", "java虚拟机", "j v m"],
        "JIT": ["jit", "j i t", "just in time", "即时编译", "即使编译"],
        "GC": ["gc", "g c", "垃圾回收", "辣鸡回收", "垃圾收集"],
        "G1": ["g1", "g一", "g 1", "g one"],
        "CMS": ["cms", "c m s", "cms收集器"],
        "ZGC": ["zgc", "z g c", "z gc"],
        "Shenandoah": ["shenandoah", "蛇纳豆阿", "shenan doah"],
        "Minor GC": ["minor gc", "minor g c", "麦呢gc", "年轻代gc"],
        "Major GC": ["major gc", "major g c", "major gc", "老年代gc"],
        "Full GC": ["full gc", "full g c", "full gc", "全gc"],
        "堆内存": ["堆内存", "对内存", "堆内层"],
        "栈内存": ["栈内存", "站内存", "站内层"],
        "方法区": ["方法区", "方法曲", "方发区"],
        "元空间": ["元空间", "原空间", "圆空间", "metaspace", "美他space"],
        "类加载器": ["类加载器", "累加载气", "classloader", "克拉斯楼的"],
        "双亲委派": ["双亲委派", "双清委派", "双亲尾派"],
        "OOM": ["oom", "o o m", "out of memory", "内存溢出", "内存益处"],
        "STW": ["stw", "s t w", "stop the world", "stop world", "斯到普theworld"],

        # ── 并发 ──
        "线程安全": ["线程安全", "线层安全", "现成安全"],
        "synchronized": ["synchronized", "s y n c h r o n i z e d", "森克耐兹的", "sync耐兹的"],
        "ReentrantLock": ["reentrantlock", "reentrant lock", "瑞因创lock", "可重入锁"],
        "volatile": ["volatile", "v o l a t i l e", "沃了太欧", "vola tile"],
        "CAS": ["cas", "c a s", "卡斯", "c a s"],
        "AQS": ["aqs", "a q s", "a q s", "a q s"],
        "线程池": ["线程池", "线层池", "现成迟", "thread pool", "斯瑞的铺"],
        "ThreadLocal": ["threadlocal", "thread local", "斯瑞的local", "thread local"],
        "ConcurrentHashMap": ["concurrenthashmap", "concurrent hashmap", "康卡瑞特hashmap", "并发hashmap"],
        "CountDownLatch": ["countdownlatch", "countdown latch", "康down latch", "倒计时门闩"],
        "CyclicBarrier": ["cyclicbarrier", "cyclic barrier", "赛克立克barrier", "回环屏障"],
        "Semaphore": ["semaphore", "赛马佛", "信号量"],
        "BlockingQueue": ["blockingqueue", "blocking queue", "blocking queue", "阻塞队列"],
        "CopyOnWrite": ["copyonwrite", "copy on write", "copy on write", "写时复制"],
        "ForkJoin": ["forkjoin", "fork join", "fork join", "分支合并"],
        "CompletableFuture": ["completablefuture", "completable future", "康普利特保future", "可完成future"],
        "死锁": ["死锁", "思索", "死所"],
        "活锁": ["活锁", "或锁", "火锁"],
        "饥饿": ["饥饿", "鸡饿", "基饿"],

        # ── 集合框架 ──
        "ArrayList": ["arraylist", "array list", "阿瑞list", "array李斯特"],
        "LinkedList": ["linkedlist", "linked list", "link李斯特", "linked list"],
        "HashMap": ["hashmap", "hash map", "哈西map", "hash map"],
        "TreeMap": ["treemap", "tree map", "tree map", "树map"],
        "LinkedHashMap": ["linkedhashmap", "linked hashmap", "link哈西map"],
        "HashSet": ["hashset", "hash set", "哈西set", "hash赛特"],
        "TreeSet": ["treeset", "tree set", "tree set", "树set"],
        "Vector": ["vector", "v e c t o r", "维克特", "vector"],
        "Stack": ["stack", "s t a c k", "斯达克", "stack"],
        "Queue": ["queue", "q u e u e", "Q", "queue"],
        "Deque": ["deque", "d e q u e", "迪Q", "deque"],

        # ── Spring 全家桶 ──
        "Spring": ["spring", "s p r i n g", "斯普瑞", "四普ring", "死普ring", "spring框架"],
        "Spring Boot": ["springboot", "spring boot", "斯普瑞布特", "spring不特", "spring布特", "springboot"],
        "Spring MVC": ["springmvc", "spring mvc", "斯普瑞mvc", "spring m v c"],
        "Spring Cloud": ["springcloud", "spring cloud", "斯普瑞cloud", "spring克劳的"],
        "IoC": ["ioc", "i o c", "控制反转", "爱o c"],
        "DI": ["di", "d i", "依赖注入", "迪"],
        "AOP": ["aop", "a o p", "面向切面", "a o p", "诶o p"],
        "Bean": ["bean", "b e a n", "宾", "being", "be an"],
        "Autowired": ["autowired", "auto wired", "奥托歪耳", "@autowired"],
        "Component": ["component", "康姆剖嫩特", "component", "@component"],
        "Service": ["service", "色维斯", "service", "@service"],
        "Repository": ["repository", "repo sit ory", "瑞剖色特瑞", "@repository"],
        "Controller": ["controller", "康错乐", "controller", "@controller"],
        "RequestMapping": ["requestmapping", "request mapping", "瑞快斯特迈品", "@requestmapping"],
        "GetMapping": ["getmapping", "get mapping", "get迈品", "@getmapping"],
        "PostMapping": ["postmapping", "post mapping", "post迈品", "@postmapping"],
        "Transactional": ["transactional", "transac tional", "川赛克神no", "@transactional", "事务注解"],
        "Aspect": ["aspect", "a s p e c t", "阿spec", "切面", "@aspect"],
        "ApplicationContext": ["applicationcontext", "application context", "application康泰克斯"],

        # ── Spring Cloud 组件 ──
        "Eureka": ["eureka", "e u r e k a", "优瑞卡", "yurika", "eureka注册中心"],
        "Nacos": ["nacos", "n a c o s", "那扣斯", "拿扣斯", "nacos"],
        "Consul": ["consul", "c o n s u l", "康搜", "consul"],
        "Ribbon": ["ribbon", "r i b b o n", "瑞本", "ribbon", "ribbon"],
        "Feign": ["feign", "f e i g n", "飞恩", "feign", "feign"],
        "OpenFeign": ["openfeign", "open feign", "欧本feign"],
        "Hystrix": ["hystrix", "h y s t r i x", "海斯trix", "histrix", "hystrix断路器"],
        "Sentinel": ["sentinel", "s e n t i n e l", "森提诺", "sentinel", "sentinel"],
        "Gateway": ["gateway", "gate way", "给特威", "盖特伟", "网关"],
        "Zuul": ["zuul", "z u u l", "祖欧", "zuul"],
        "Config": ["config", "c o n f i g", "康飞哥", "config", "配置中心"],
        "Bus": ["bus", "b u s", "巴斯", "bus", "消息总线"],
        "Sleuth": ["sleuth", "s l e u t h", "斯路斯", "sleuth", "链路追踪"],
        "Zipkin": ["zipkin", "z i p k i n", "贼pkin", "zipkin"],
        "SkyWalking": ["skywalking", "sky walking", "sky walking", "天walking"],

        # ── 持久层 ──
        "MyBatis": ["mybatis", "my batis", "买贝提斯", "m y b a t i s", "卖巴提斯"],
        "MyBatis-Plus": ["mybatisplus", "mybatis plus", "买贝提斯plus"],
        "Hibernate": ["hibernate", "h i b e r n a t e", "海博内特", "hibernate", "high博内特"],
        "JPA": ["jpa", "j p a", "jpa", "j pa", "杰p a"],
        "JDBC": ["jdbc", "j d b c", "jdbc", "j d b c"],
        "连接池": ["连接池", "年接池", "连街迟", "connection pool"],
        "HikariCP": ["hikaricp", "hikari cp", "海卡瑞cp", "hikaricp"],
        "Druid": ["druid", "d r u i d", "朱瑞的", "druid", "德鲁伊"],
        "DataSource": ["datasource", "data source", "data source", "数据源"],
        "分库分表": ["分库分表", "粉库粉表", "sharding", "沙丁"],
        "ShardingSphere": ["shardingsphere", "sharding sphere", "沙丁sphere", "shardingsphere"],
        "读写分离": ["读写分离", "读写分利", "毒写分离"],

        # ── 微服务 ──
        "分布式事务": ["分布式事务", "分不式事务", "分布式4务", "distributed transaction"],
        "Seata": ["seata", "s e a t a", "希塔", "seata"],
        "TCC": ["tcc", "t c c", "tcc事务"],
        "SAGA": ["saga", "s a g a", "萨嘎", "saga事务"],
        "XA": ["xa", "x a", "xa协议", "x a协议"],
        "CAP": ["cap", "c a p", "cap理论", "cap定理"],
        "BASE": ["base", "b a s e", "base理论", "贝斯理论"],
        "服务注册": ["服务注册", "扶务注册", "服务注测"],
        "服务发现": ["服务发现", "扶务发现", "服务花现"],
        "负载均衡": ["负载均衡", "负载均很", "负在均衡"],
        "熔断": ["熔断", "容断", "融短", "circuit breaker"],
        "降级": ["降级", "蒋级", "讲级"],
        "限流": ["限流", "现流", "线留", "rate limit"],
        "网关": ["网关", "网官", "王关", "gateway"],
        "配置中心": ["配置中心", "培制中心", "陪置中心", "config center"],
        "链路追踪": ["链路追踪", "练路追踪", "连路追中"],
        "日志收集": ["日志收集", "日字收集", "log收集"],
        "服务网格": ["服务网格", "扶务网格", "service mesh", "色维斯卖食"],

        # ── 消息队列 ──
        "Kafka": ["kafka", "卡夫卡", "k a f k a"],
        "RabbitMQ": ["rabbitmq", "rabbit mq", "rabbit m q", "瑞比特mq"],
        "RocketMQ": ["rocketmq", "rocket mq", "罗克特mq", "rocket m q"],
        "Pulsar": ["pulsar", "p u l s a r", "抛萨", "pulsar", "pulsar"],
        "生产者": ["生产者", "生产者", "producer", "普柔丢色"],
        "消费者": ["消费者", "消费者", "consumer", "康苏门"],
        "Broker": ["broker", "b r o k e r", "布肉克", "broker"],
        "Topic": ["topic", "t o p i c", "套匹克", "topic"],
        "Partition": ["partition", "part ition", "帕提神", "partition", "分区"],
        "Consumer Group": ["consumergroup", "consumer group", "康苏门group"],

        # ── Redis ──
        "Redis": ["redis", "r e d i s", "瑞迪斯", "redis", "red is"],
        "缓存穿透": ["缓存穿透", "缓存串透", "缓存穿偷"],
        "缓存击穿": ["缓存击穿", "缓存机穿"],
        "缓存雪崩": ["缓存雪崩", "缓存雪奔"],
        "分布式锁": ["分布式锁", "分布锁", "distributed lock", "迪斯吹比锁"],
        "Redisson": ["redisson", "r e d i s s o n", "瑞迪森", "redisson"],
        "Jedis": ["jedis", "j e d i s", "杰迪斯", "jedis"],
        "Lettuce": ["lettuce", "l e t t u c e", "莱特斯", "lettuce"],
        "RDB": ["rdb", "r d b", "rdb持久化"],
        "AOF": ["aof", "a o f", "aof持久化"],
        "哨兵": ["哨兵", "少兵", "烧饼", "sentinel"],
        "集群": ["集群", "鸡群", "集权", "cluster", "克拉斯德"],
        "主从": ["主从", "竹从", "主虫", "master slave"],

        # ── 数据库 ──
        "MySQL": ["mysql", "my sql", "my s q l", "买sql", "买sequel"],
        "InnoDB": ["innodb", "inno db", "因no db", "i n n o d b"],
        "MyISAM": ["myisam", "my isam", "买aisam", "m y i s a m"],
        "B+树": ["b加树", "b加数", "b+树", "b+数", "b plus树"],
        "聚簇索引": ["聚簇索引", "剧促索引", "clustered index"],
        "非聚簇索引": ["非聚簇索引", "飞聚簇索引", "non clustered index"],
        "覆盖索引": ["覆盖索引", "覆盖所引", "covering index"],
        "最左前缀": ["最左前缀", "最左前追", "leftmost prefix"],
        "回表": ["回表", "会表", "回标"],
        "索引下推": ["索引下推", "所引下推", "index condition pushdown"],
        "MVCC": ["mvcc", "m v c c", "多版本并发控制"],
        "间隙锁": ["间隙锁", "间细锁", "gap lock", "该普lock"],
        "临键锁": ["临键锁", "林建锁", "next key lock"],
        "意向锁": ["意向锁", "一项锁", "intention lock"],
        "慢查询": ["慢查询", "慢查寻", "slow query", "斯洛快瑞"],
        "Explain": ["explain", "e x p l a i n", "一克斯plain", "explain"],
        "执行计划": ["执行计划", "直行计划", "execution plan"],
        "事务隔离": ["事务隔离", "事务隔离", "isolation level", "爱索雷神level"],
        "读已提交": ["读已提交", "毒已提交", "read committed"],
        "可重复读": ["可重复读", "可重复毒", "repeatable read"],
        "串行化": ["串行化", "串形化", "serializable", "希尔来泽波"],

        # ── 大数据 ──
        "Hadoop": ["hadoop", "h a d o o p", "哈杜普", "hadoop", "哈都普"],
        "HDFS": ["hdfs", "h d f s", "hdfs"],
        "MapReduce": ["mapreduce", "map reduce", "迈普瑞丢斯", "map reduce"],
        "Hive": ["hive", "h i v e", "海夫", "hive", "哈一夫"],
        "Spark": ["spark", "s p a r k", "斯帕克", "spark"],
        "Flink": ["flink", "f l i n k", "福林克", "flink"],
        "HBase": ["hbase", "h base", "h base", "h贝斯"],
        "ZooKeeper": ["zookeeper", "zoo keeper", "租keeper", "zoo keeper", "z k"],
        "Elasticsearch": ["elasticsearch", "elastic search", "伊莱斯提search", "es", "e s"],
        "Logstash": ["logstash", "log stash", "log斯达西", "logstash"],
        "Kibana": ["kibana", "k i b a n a", "可比那", "kibana"],
        "ELK": ["elk", "e l k", "elk"],
        "Storm": ["storm", "s t o r m", "斯多姆", "storm"],
        "Presto": ["presto", "p r e s t o", "普瑞斯头", "presto"],
        "Doris": ["doris", "d o r i s", "多瑞斯", "doris"],
        "ClickHouse": ["clickhouse", "click house", "克立克house", "click house"],
        "数据湖": ["数据湖", "数具湖", "素据湖", "data lake"],
        "数据仓库": ["数据仓库", "数具仓库", "素具仓库", "data warehouse"],

        # ── Maven / Gradle ──
        "Maven": ["maven", "m a v e n", "美文", "马文", "maven"],
        "Gradle": ["gradle", "g r a d l e", "格瑞斗", "gradle", "grado"],
        "pom.xml": ["pomxml", "pom xml", "pom点xml", "pom文件"],
        "依赖管理": ["依赖管理", "一赖管理", "以来管理", "dependency management"],
        "仓库": ["仓库", "仓库", "repository", "瑞剖色特瑞"],
        "Snapshot": ["snapshot", "snap shot", "snap shot", "快照版本"],
        "生命周期": ["生命周期", "lifecycle", "来夫赛口"],
        "插件": ["插件", "插件", "plugin", "普拉gin"],

        # ── 测试 ──
        "JUnit": ["junit", "j unit", "j unit", "j unit", "junit"],
        "Mockito": ["mockito", "mo ki to", "莫克头", "mockito"],
        "PowerMock": ["powermock", "power mock", "炮儿mock"],
        "AssertJ": ["assertj", "assert j", "阿色特j"],
        "Hamcrest": ["hamcrest", "ham crest", "汉姆克瑞斯特"],
        "集成测试": ["集成测试", "基层测试", "integration test"],
        "单元测试": ["单元测试", "单员策略", "unit test"],

        # ── Android ──
        "Android": ["android", "a n d r o i d", "安卓", "android", "暗卓"],
        "Kotlin": ["kotlin", "k o t l i n", "科特林", "kotlin"],
        "Jetpack": ["jetpack", "jet pack", "杰特pack"],
        "Activity": ["activity", "ac ti vity", "activity", "爱克提威体"],
        "Fragment": ["fragment", "frag ment", "福瑞格门特"],
        "ViewModel": ["viewmodel", "view model", "viu model"],
        "LiveData": ["livedata", "live data", "live data"],
        "Room": ["room", "r o o m", "room", "room数据库"],
        "Retrofit": ["retrofit", "retro fit", "瑞特fit"],
        "OkHttp": ["okhttp", "ok http", "ok http"],
        "Glide": ["glide", "g l i d e", "格莱的", "glide"],
        "Compose": ["compose", "com pose", "compose", "jetpack compose"],

        # ── 设计模式（Java 实现） ──
        "单例模式": ["单例模式", "单立模式", "单利模式", "singleton", "singleton"],
        "工厂模式": ["工厂模式", "工厂磨石", "factory pattern", "工厂方法"],
        "抽象工厂": ["抽象工厂", "抽像工厂", "abstract factory"],
        "建造者模式": ["建造者模式", "建赵者模式", "builder pattern"],
        "原型模式": ["原型模式", "圆形模式", "prototype pattern"],
        "适配器模式": ["适配器模式", "式配器模式", "adapter pattern", "阿呆普特"],
        "装饰器模式": ["装饰器模式", "装时期模式", "decorator pattern"],
        "代理模式": ["代理模式", "呆理模式", "proxy pattern"],
        "观察者模式": ["观察者模式", "观察折模式", "observer pattern", "奥布斯瓦"],
        "策略模式": ["策略模式", "策略磨石", "strategy pattern", "斯抓特基"],
        "模板方法": ["模板方法", "母版方法", "template method", "坦普雷特"],
        "责任链": ["责任链", "择任链", "responsibility chain", "chain of responsibility"],

        # ── 杂项 ──
        "序列化": ["序列化", "序列画", "serializable", "希尔来泽波"],
        "反序列化": ["反序列化", "返序列画", "deserialize"],
        "注解": ["注解", "朱解", "annotation", "安诺忒神"],
        "反射": ["反射", "反射", "reflection", "瑞福莱克神"],
        "泛型": ["泛型", "范型", "凡行", "反省", "generic", "基奈瑞克"],
        "枚举": ["枚举", "没举", "美举", "每年", "enum", "一纳姆"],
        "动态代理": ["动态代理", "动态呆理", "dynamic proxy"],
        "字节码": ["字节码", "字杰马", "bytecode", "拜特扣的"],
        "热部署": ["热部署", "热不熟", "hot deploy"],
        "灰度发布": ["灰度发布", "回度发布", "灰杜发不", "gray release"],
        "蓝绿部署": ["蓝绿部署", "蓝绿不熟", "blue green deploy"],
        "滚动发布": ["滚动发布", "滚动发不", "rolling deploy"],
        "优雅停机": ["优雅停机", "优压低级", "graceful shutdown"],

        # ── Java 8+ 新特性 ──
        "Lambda": ["lambda", "l a m b d a", "兰布达", "拉姆达", "lam达", "lambda表达式"],
        "Stream": ["stream", "s t r e a m", "斯追m", "stream流", "stream API", "stream api"],
        "Optional": ["optional", "option al", "奥普申no", "optional类", "optional"],
        "函数式接口": ["函数式接口", "函数式接口", "functional interface", "方格申no interface"],
        "Predicate": ["predicate", "pre dicate", "普瑞迪克特", "predicate"],
        "Consumer": ["consumer", "con sumer", "康苏门", "consumer接口"],
        "Supplier": ["supplier", "sup plier", "色普莱尔", "supplier接口"],
        "Function": ["function", "func tion", "方格申", "function接口"],
        "方法引用": ["方法引用", "方法引yong", "method reference", "method ref", "双冒号"],
        "默认方法": ["默认方法", "默认方法", "default method", "迪佛特方法"],
        "LocalDate": ["localdate", "local date", "楼口date"],
        "LocalTime": ["localtime", "local time", "楼口time"],
        "LocalDateTime": ["localdatetime", "local date time", "楼口datetime"],
        "Instant": ["instant", "in stant", "因斯贪特", "instant"],
        "Record": ["record", "r e c o r d", "瑞扣的", "record类", "record", "记录类"],
        "Sealed Class": ["sealedclass", "sealed class", "see欧的class", "密封类"],
        "Pattern Matching": ["patternmatching", "pattern matching", "帕腾迈青", "模式匹配"],
        "Virtual Threads": ["virtualthreads", "virtual threads", "问道threads", "虚拟线程", "virtual thread", "project loom", "普若杰克特路母"],
        "Switch Expression": ["switchexpression", "switch expression", "switch表达式", "switch express"],
        "Text Block": ["textblock", "text block", "text block", "文本块"],
        "Var": ["var", "v a r", "瓦", "var关键字"],

        # ── 网络 / IO ──
        "Netty": ["netty", "n e t t y", "内提", "netty", "netty框架"],
        "NIO": ["nio", "n i o", "n i o", "new io", "new i o", "nio"],
        "BIO": ["bio", "b i o", "bio"],
        "AIO": ["aio", "a i o", "aio"],
        "ByteBuffer": ["bytebuffer", "byte buffer", "byte buffer"],
        "Channel": ["channel", "chan nel", "channel", "channel"],
        "Selector": ["selector", "se lector", "selector", "selector", "多路复用"],
        "零拷贝": ["零拷贝", "0拷贝", "zero copy", "zero copy"],
        "epoll": ["epoll", "e p o l l", "i poll", "epoll"],

        # ── 服务器 / 容器 ──
        "Tomcat": ["tomcat", "tom cat", "汤姆cat", "tomcat", "tomcat", "tomcat"],
        "Jetty": ["jetty", "j e t t y", "杰提", "jetty"],
        "Undertow": ["undertow", "under tow", "安德头", "undertow"],
        "Servlet": ["servlet", "serv let", "色vlet", "servlet", "servlet"],
        "Filter": ["filter", "fil ter", "飞欧特", "filter", "过滤器"],
        "Interceptor": ["interceptor", "inter ceptor", "因特塞普特", "拦截器"],

        # ── RPC / 服务框架 ──
        "Dubbo": ["dubbo", "d u b b o", "杜博", "dubbo", "dubbo", "达博"],
        "gRPC": ["grpc", "g r p c", "g rpc", "grpc", "grpc"],
        "Protobuf": ["protobuf", "proto buf", "普若托buf", "protobuf"],
        "Thrift": ["thrift", "t h r i f t", "斯瑞福特", "thrift"],
        "Hessian": ["hessian", "h e s s i a n", "黑神", "hessian"],

        # ── 工具库 ──
        "Lombok": ["lombok", "l o m b o k", "龙博客", "lombok", "lombok"],
        "MapStruct": ["mapstruct", "map struct", "迈普斯抓克特", "mapstruct"],
        "Jackson": ["jackson", "j a c k s o n", "杰克森", "jackson"],
        "Gson": ["gson", "g s o n", "gson", "gson", "g森"],
        "Fastjson": ["fastjson", "fast json", "fast json", "fastjson"],
        "SLF4J": ["slf4j", "s l f 4 j", "slf4 j", "slf4j", "slf for j"],
        "Logback": ["logback", "log back", "log back", "logback"],
        "Log4j2": ["log4j2", "log4j 2", "log for j2", "log4j"],
        "Guava": ["guava", "g u a v a", "瓜娃", "guava", "guava"],
        "Apache Commons": ["apachecommons", "apache commons", "阿帕奇commons"],
        "Hutool": ["hutool", "hu tool", "胡tool", "hutool"],

        # ── 定时任务 ──
        "Quartz": ["quartz", "q u a r t z", "夸兹", "quartz"],
        "XXL-Job": ["xxljob", "xxl job", "x x l job", "xxl-job"],
        "Elastic-Job": ["elasticjob", "elastic job", "elastic job"],
        "Cron": ["cron", "c r o n", "克容", "cron表达式"],

        # ── 限流 / 熔断 ──
        "令牌桶": ["令牌桶", "令牌同", "token bucket"],
        "漏桶": ["漏桶", "漏同", "leaky bucket"],
        "滑动窗口": ["滑动窗口", "滑动串口", "华动窗口"],
        "计数器": ["计数器", "记数器", "counter"],
        "Guava RateLimiter": ["guava ratelimiter", "guava rate limiter", "瓜娃rate limiter"],

        # ── 运维 / 诊断 ──
        "Arthas": ["arthas", "a r t h a s", "阿萨斯", "arthas"],
        "jstack": ["jstack", "j stack", "jstack", "j stack"],
        "jmap": ["jmap", "j map", "jmap", "j map"],
        "jstat": ["jstat", "j stat", "jstat", "j stat"],
        "jconsole": ["jconsole", "j console", "jconsole", "j console"],
        "VisualVM": ["visualvm", "visual vm", "visual vm"],
        "JProfiler": ["jprofiler", "j profiler", "j profiler"],
        "MAT": ["mat", "m a t", "mat", "memory analyzer"],
        "JVM参数": ["jvm参数", "jvm参数", "xmx", "x m x", "xms", "x m s", "xss", "x s s"],

        # ── 安全 ──
        "Spring Security": ["springsecurity", "spring security", "斯普瑞security"],
        "OAuth2": ["oauth2", "o auth2", "oauth 2", "o auth 2.0"],
        "认证": ["认证", "人证", "authentication", "奥森提k神"],
        "授权": ["授权", "受权", "authorization", "奥色瑞z神"],
        "RBAC": ["rbac", "r b a c", "rbac"],
        "JWT": ["jwt", "j w t", "jwt"],
        "Filter Chain": ["filterchain", "filter chain", "filter chain", "过滤器链"],

        # ── 并发补充 ──
        "ReadWriteLock": ["readwritelock", "read write lock", "read write lock", "读写锁"],
        "ReentrantReadWriteLock": ["reentrantreadwritelock", "reentrant read write lock", "瑞因创read write lock"],
        "StampedLock": ["stampedlock", "stamped lock", "stamped lock"],
        "Executors": ["executors", "exe cutors", "executors", "一克斯Q特"],
        "ExecutorService": ["executorservice", "executor service", "executor service"],
        "Callable": ["callable", "call able", "callable", "callable"],
        "Runnable": ["runnable", "run nable", "软那波", "runnable"],
        "FutureTask": ["futuretask", "future task", "future task", "飞优切task"],
        "Disruptor": ["disruptor", "dis rup tor", "迪斯ruptor", "disruptor"],
        "HappensBefore": ["happensbefore", "happens before", "happens before", "哈盆before"],
        "TLAB": ["tlab", "t l a b", "tlab", "tlab"],

        # ── API 文档 / 测试 ──
        "Swagger": ["swagger", "s w a g g e r", "斯外格", "swagger"],
        "OpenAPI": ["openapi", "open api", "open api", "欧本api"],
        "Knife4j": ["knife4j", "knife 4j", "knife for j", "knife4j"],
        "YApi": ["yapi", "y api", "y api", "yapi"],
        "Postman": ["postman", "post man", "post man", "postman"],
        "JMeter": ["jmeter", "j meter", "j meter", "jmeter"],
        "压力测试": ["压力测试", "压力策试", "stress test"],
        "性能测试": ["性能测试", "性能策略", "performance test"],

        # ── DevOps ──
        "Docker": ["docker", "d o c k e r", "达克", "dock", "doctor", "docker"],
        "Kubernetes": ["kubernetes", "k u b e r n e t e s", "k8s", "k 8 s", "k八s", "库博内提斯"],
        "Jenkins": ["jenkins", "j e n k i n s", "金肯斯", "jenkins", "jenkins"],
        "GitLab CI": ["gitlabci", "gitlab ci", "gitlab c i", "gitlab ci cd"],
        "GitHub Actions": ["githubactions", "github actions", "github action", "github action"],
        "Ansible": ["ansible", "a n s i b l e", "安色波", "ansible"],
        "Terraform": ["terraform", "t e r r a f o r m", "泰若form", "terraform"],
        "Helm": ["helm", "h e l m", "海姆", "helm"],
        "Prometheus": ["prometheus", "pro metheus", "普若米修斯", "prometheus"],
        "Grafana": ["grafana", "g r a f a n a", "格拉法那", "grafana", "格拉法纳"],

        # ── 微服务补充 ──
        "API网关": ["api网关", "api网关", "api gateway", "api getaway"],
        "BFF": ["bff", "b f f", "bff", "backend for frontend"],
        "DDD": ["ddd", "d d d", "domain driven design", "领域驱动设计"],
        "CQRS": ["cqrs", "c q r s", "cqrs", "命令查询职责分离"],
        "Event Sourcing": ["eventsourcing", "event sourcing", "事件溯源"],
        "Saga": ["saga", "s a g a", "萨嘎", "saga模式"],
        "Strangler": ["strangler", "strangler", "斯串格勒", "绞杀者模式"],

        # ── 消息中间件深度 ──
        "消息中间件": ["消息中间件", "消息中间键", "消息中坚件", "message middleware"],
        "RocketMQ集群": ["rocketmq集群", "rocket mq集群", "rocketmq cluster"],
        "RocketMQ事务消息": ["rocketmq事务消息", "rocketmq事务", "transaction message"],
        "RabbitMQ交换机": ["rabbitmq交换机", "rabbitmq exchange", "rabbit exchange"],
        "死信队列": ["死信队列", "死信对列", "dead letter queue", "DLQ", "d l q"],
        "延迟队列": ["延迟队列", "延迟对列", "delay queue"],
        "消息堆积": ["消息堆积", "消息堆鸡", "message backlog"],
        "消息回溯": ["消息回溯", "消息回速", "message replay"],
        "消息去重": ["消息去重", "消息去虫", "消息去除", "message dedup"],
        "顺序消息": ["顺序消息", "顺序消息", "ordered message"],
        "广播消费": ["广播消费", "broadcasting", "broadcast消费"],
        "集群消费": ["集群消费", "cluster消费", "clustering消费"],
        "Tag过滤": ["tag过滤", "tag过绿", "tag filter"],
        "重试队列": ["重试队列", "重试对列", "retry queue"],
        "Pull模式": ["pull模式", "pull模式", "pull", "拉模式"],
        "Push模式": ["push模式", "push模式", "push", "推模式"],
        "NameServer": ["nameserver", "name server", "name server", "name server"],
        "Broker主从": ["broker主从", "broker主虫", "broker master slave"],
        "同步刷盘": ["同步刷盘", "同步刷", "sync flush"],
        "异步刷盘": ["异步刷盘", "async flush"],

        # ── K8s/容器深度 ──
        "容器化": ["容器化", "容器画", "containerization", "康特呢瑞z神"],
        "Dockerfile": ["dockerfile", "docker file", "docker file"],
        "Docker Compose": ["dockercompose", "docker compose", "docker compose", "docker compose"],
        "镜像仓库": ["镜像仓库", "镜像仓库", "image registry", "registery"],
        "Pod": ["pod", "p o d", "pad", "pod", "pod"],
        "Deployment": ["deployment", "de ploy ment", "deployment", "迪普洛伊门特", "deployment"],
        "Service": ["service", "色维斯", "service", "service", "service"],
        "ConfigMap": ["configmap", "config map", "config map", "config map"],
        "Secret": ["secret", "s e c r e t", "色克瑞特", "secret"],
        "Ingress": ["ingress", "in gress", "英格瑞斯", "ingress"],
        "PersistentVolume": ["persistentvolume", "persistent volume", "persistent volume", "PV", "p v"],
        "PersistentVolumeClaim": ["persistentvolumeclaim", "persistent volume claim", "PVC", "p v c"],
        "StatefulSet": ["statefulset", "stateful set", "stateful set", "有状态set"],
        "DaemonSet": ["daemonset", "daemon set", "daemon set", "守护set"],
        "HPA": ["hpa", "h p a", "hpa", "水平扩缩容"],
        "VPA": ["vpa", "v p a", "vpa", "垂直扩缩容"],
        "Service Mesh": ["servicemesh", "service mesh", "service mesh", "服务网格"],
        "Istio": ["istio", "i s t i o", "伊斯提欧", "istio"],
        "Envoy": ["envoy", "e n v o y", "恩沃伊", "envoy"],
        "Helm Chart": ["helmchart", "helm chart", "helm chart", "海姆chart"],
        "RBAC": ["rbac", "r b a c", "rbac", "基于角色访问控制"],
        "ServiceAccount": ["serviceaccount", "service account", "service account"],
        "Namespace": ["namespace", "name space", "name space", "命名空间", "内姆space"],
        "Kubelet": ["kubelet", "ku be let", "kubelet", "库伯莱特"],
        "Kube-proxy": ["kubeproxy", "kube proxy", "kube proxy", "kube proxy"],
        "etcd": ["etcd", "e t c d", "etcd", "i t c d"],
        "kubectl": ["kubectl", "ku be ctl", "库伯ctl", "kubectl", "kube控制"],
        "Kubeadm": ["kubeadm", "kube adm", "kube adm", "kubeadm"],
        "Minikube": ["minikube", "mini kube", "迷你kube", "minikube"],
        "Kind": ["kind", "k i n d", "kind", "k in d"],

        # ── MySQL 深度 ──
        "ACID": ["acid", "a c i d", "acid性质", "acid", "atomicity"],
        "原子性": ["原子性", "atomicity", "阿托米city", "原子性"],
        "一致性": ["一致性", "consistency", "康西斯tency", "一致性"],
        "隔离性": ["隔离性", "isolation", "爱索雷神", "隔离性"],
        "持久性": ["持久性", "durability", "丢若bility", "持久性"],
        "脏读": ["脏读", "脏毒", "dirty read", "dirty read"],
        "不可重复读": ["不可重复读", "non repeatable read", "non repeatable read"],
        "幻读": ["幻读", "患读", "phantom read", "换读"],
        "Undo Log": ["undolog", "undo log", "undo log", "安度log"],
        "Redo Log": ["redolog", "redo log", "redo log", "瑞度log"],
        "Binlog": ["binlog", "bin log", "bin log", "binary log", "二进志log"],
        "Double Write": ["doublewrite", "double write", "double write", "双写"],
        "Change Buffer": ["changebuffer", "change buffer", "change buffer"],
        "Adaptive Hash": ["adaptivehash", "adaptive hash", "自适应哈希"],
        "Insert Buffer": ["insertbuffer", "insert buffer", "insert buffer"],
        "两次写": ["两次写", "两ci写", "double write", "两次写"],
        "表空间": ["表空间", "tablespace", "table space", "table space"],
        "段": ["段", "segment", "赛格门特"],
        "区": ["区", "extent", "extent", "extent"],
        "页": ["页", "page", "page", "佩奇", "16k页"],
        "行格式": ["行格式", "row format", "row format", "raw format"],
        "Compact": ["compact", "com pact", "compact", "compact", "紧凑格式"],
        "Dynamic": ["dynamic", "dy namic", "dynamic", "动态格式"],
        "Compressed": ["compressed", "com pressed", "compressed", "压缩格式"],
        "字符集": ["字符集", "charset", "char set", "utf8", "u t f 8", "utf8mb4", "utf8 mb4"],
        "排序规则": ["排序规则", "collation", "collation", "考雷神"],
        "联合索引": ["联合索引", "连合索引", "联和所引", "composite index"],
        "前缀索引": ["前缀索引", "前追所引", "prefix index"],
        "全文索引": ["全文索引", "全文所引", "fulltext index"],
        "哈希索引": ["哈希索引", "哈西所引", "hash index"],
        "空间索引": ["空间索引", "空间所引", "spatial index", "R树索引"],
        "force index": ["forceindex", "force index", "force index", "强制索引"],
        "use index": ["useindex", "use index", "use index"],
        "ignore index": ["ignoreindex", "ignore index", "ignore index"],
        "filesort": ["filesort", "file sort", "file sort", "文件排序"],
        "temporary table": ["temporarytable", "temporary table", "temporary table", "临时表"],
        "ICP": ["icp", "i c p", "index condition pushdown", "索引条件下推"],
        "MRR": ["mrr", "m r r", "multi range read", "mrr"],
        "BKA": ["bka", "b k a", "batched key access", "bka"],
        "BNL": ["bnl", "b n l", "block nested loop", "bnl"],
        "锁升级": ["锁升级", "鎖升级", "lock escalation"],
        "死锁检测": ["死锁检测", "死锁检ce", "deadlock detection"],
        "pt-query-digest": ["ptquerydigest", "pt query digest", "pt query digest", "percona toolkit"],
        "慢查询日志": ["慢查询日志", "慢查寻日志", "slow query log", "slow log"],
        "general log": ["generallog", "general log", "general log"],
        "error log": ["errorlog", "error log", "error log", "错误日志"],
        "连接数": ["连接数", "年接数", "connections", "connections"],
        "thread cache": ["threadcache", "thread cache", "thread cache", "线程缓存"],
        "Table Cache": ["tablecache", "table cache", "table cache", "表缓存"],
        "Query Cache": ["querycache", "query cache", "query cache", "查询缓存", "快取"],
        "InnoDB Buffer Pool": ["innodbbufferpool", "innodb buffer pool", "buffer pool", "buffer铺"],
        "AIO": ["aio", "a i o", "async io", "异步IO"],
        "PIO": ["pio", "p i o", "同步IO"],
        "FIO": ["fio", "f i o", "file io"],
        "XA事务": ["xa事务", "xa 事务", "x a事务", "xa transaction"],
        "GTID": ["gtid", "g t i d", "global transaction id", "g t i d"],
        "半同步复制": ["半同步复制", "semi sync", "semi sync replication"],
        "组复制": ["组复制", "group replication", "mgr", "m g r"],
        "InnoDB Cluster": ["innodbcluster", "innodb cluster", "innodb cluster", "inno cluster"],
        "Orchestrator": ["orchestrator", "or ches tra tor", "奥凯斯追特", "orchestrator"],
        "ProxySQL": ["proxysql", "proxy sql", "proxy sql", "proxy sql"],
        "MyCat": ["mycat", "my cat", "my cat", "mycat"],
        "Sharding-JDBC": ["shardingjdbc", "sharding jdbc", "沙丁jdbc"],
        "Vitess": ["vitess", "v i t e s s", "vi泰斯", "vitess"],
        "TiDB": ["tidb", "ti d b", "t i d b", "tidb", "t i db"],
        "OceanBase": ["oceanbase", "ocean base", "ocean base", "欧神base"],
        "PolarDB": ["polardb", "polar db", "polar db", "pole db"],
        "TDSQL": ["tdsql", "t d sql", "t d s q l", "tdsql"],
    },
}
