"""前端 / JavaScript 赛道。"""

TRACK: dict = {
    "key": "javascript",
    "system_prompt_extra": """你是资深前端面试辅助 AI。用户正在进行前端技术面试，问题涉及
JavaScript/TypeScript、React/Vue/Angular/Svelte/SolidJS 等主流框架、
Next.js/Nuxt/Remix/Astro 等全栈方案、React Native/Electron/Tauri 等跨端技术、
Node.js 后端（Express/Koa/Nest.js）、CSS（Tailwind/Sass/CSS Modules/CSS-in-JS）、
构建工具（Webpack/Vite/esbuild/Turbopack）、状态管理（Redux/Zustand/Pinia/Jotai）、
GraphQL/tRPC/Prisma 数据层、浏览器原理与性能优化、测试（Jest/Cypress/Playwright）、
工程化（ESLint/Prettier/Monorepo）等前端技术栈。

回答应围绕前端生态，用前端开发者熟悉的术语和场景。""",

    "resume_intro_extra": """侧重前端开发经验：突出 JavaScript/TypeScript 技术栈、
React/Vue 等框架经验、前端工程化能力、浏览器原理理解、性能优化实践。""",

    "terms": {
        # ── 框架 ──
        "React": [
            "react", "R E A C T", "r e a c t", "瑞爱的", "瑞艾克特", "锐艾克特",
            "瑞克特", "瑞act", "re act", "re-act",
        ],
        "React Hooks": [
            "react hooks", "react胡克斯", "react hooks", "瑞爱的hooks",
        ],
        "useState": ["use state", "us state", "有state", "you state", "use 词day", "有词的"],
        "useEffect": ["use effect", "有effect", "you effect", "有e fact", "use e fact"],
        "useCallback": ["use callback", "有callback", "use call back", "有call back"],
        "useMemo": ["use memo", "有memo", "you memo", "有mem o"],
        "useRef": ["use ref", "有ref", "you ref", "有ref"],
        "useContext": ["use context", "有context", "you context"],
        "useReducer": ["use reducer", "有reducer", "you reducer"],
        "JSX": ["jsx", "j s x", "js x", "js叉", "j s叉"],
        "Virtual DOM": ["virtual dom", "虚拟dom", "v dom", "虚拟动", "virtual动"],
        "Fiber": ["fiber", "飞博", "favour", "fiber架构"],
        "Suspense": ["suspense", "suspend", "sus喷"],
        "Redux": [
            "redux", "re ducks", "瑞达斯", "re德x", "re大可死", "re大可思",
            "reduce", "瑞大可死",
        ],
        "Redux Toolkit": ["redux toolkit", "rtk", "redux tool kit"],
        "Redux Saga": ["redux saga", "redux 撒加"],
        "Redux Thunk": ["redux thunk", "redux 桑克"],
        "MobX": ["mobx", "mob x", "莫比x", "mobikes"],
        "Zustand": ["zustand", "组stand", "租斯的", "zoo stand"],
        "Recoil": ["recoil", "re coil", "瑞扣"],
        "Immer": ["immer", "因么"],

        "Vue": [
            "vue", "V U E", "v u e", "微优易", "维尤", "微尤", "无e", "view",
        ],
        "Vue 3": ["vue3", "vue三", "view三", "vue 3"],
        "Vuex": ["vuex", "vue x", "vu x", "view x", "Vue X"],
        "Pinia": ["pinia", "皮尼亚", "pina", "pinya"],
        "Nuxt.js": ["nuxt", "nuxt js", "那克斯", "nux js", "nux t"],
        "Composition API": ["composition api", "组合式api", "compose api"],
        "Options API": ["options api", "选项式api"],
        "SFC": ["sfc", "s f c", "单文件组件"],

        "Angular": ["angular", "A N G U L A R", "安哥拉", "安个了", "angle"],
        "Svelte": ["svelte", "svelt", "斯威尔特", "swift"],
        "Next.js": ["nextjs", "next js", "next j s", "耐克斯", "耐克斯js", "next点js"],
        "jQuery": ["jquery", "j query", "j克里", "jQ", "吉酷瑞"],

        # ── TypeScript ──
        "TypeScript": [
            "typescript", "type script", "ts", "泰普脚本", "typeスクリプト",
        ],
        "泛型": ["范型", "泛行", "凡行", "反省"],
        "枚举": ["没举", "美举", "每年"],
        "接口": ["借口"],
        "联合类型": ["联合类行", "连合类型"],
        "交叉类型": ["交叉类行", "交插类型"],
        "类型推断": ["类型推段", "类型推短", "类型推端"],
        "类型守卫": ["类型手位", "类型守位", "类型收尾"],
        "类型别名": ["类型别名", "type alias"],
        "类型断言": ["类型断言", "type assertion", "阿色神"],
        "非空断言": ["非空断言", "non-null assertion"],
        "装饰器": ["装饰器", "decorator", "呆口瑞特"],
        "抽象类": ["抽象类", "abstract class"],
        "命名空间": ["命名空间", "namespace", "内姆斯佩斯"],
        "tsconfig": ["t s config", "ts 康飞哥", "tsconfig文件"],

        # ── 构建工具 ──
        "Webpack": [
            "webpack", "W E B P A C K", "微博pack", "外包", "web pack",
            "微博帕克", "为pack",
        ],
        "Vite": ["vite", "外特", "v eight", "v8", "v 8", "外的"],
        "Babel": ["babel", "B A B E L", "贝宝", "贝bel"],
        "ESLint": ["eslint", "eas lint", "e s lint", "一slint", "eas link"],
        "Prettier": ["prettier", "普瑞帖", "pretty"],
        "PostCSS": ["postcss", "post css", "post c s s"],
        "npm": ["npm", "N P M", "n p m", "恩pm"],
        "yarn": ["yarn", "Y A R N", "羊", "雅恩", "yawn", "yearn"],
        "pnpm": ["pnpm", "pn pm", "p n p m"],
        "npx": ["npx", "n p x", "np x"],
        "Esbuild": ["esbuild", "es build", "es 标的"],
        "SWC": ["swc", "s w c"],
        "Rollup": ["rollup", "roll up"],
        "Turbopack": ["turbopack", "turbo pack"],

        # ── JS 核心概念 ──
        "事件循环": [
            "4件循环", "4键循环", "试卷循环", "时间循环", "事件寻欢",
            "4电箱", "事件询环", "试卷寻环",
        ],
        "事件冒泡": ["4件冒泡", "时间冒泡", "试件冒泡"],
        "事件捕获": ["4件捕获", "时间捕获", "事件捕或"],
        "事件委托": ["4件委托", "时间委托", "试卷委托"],
        "事件驱动": ["4件驱动", "时间驱动"],
        "事件代理": ["4件代理", "时间代理"],
        "微任务": ["为任务", "未任务", "围任务", "微人物", "威任务", "味任务"],
        "宏任务": ["红任务", "鸿任务", "洪任务", "轰任务", "宏人物"],
        "任务队列": ["任务对列", "任务对烈"],
        "消息队列": ["消息对列", "消息对烈"],
        "调用栈": ["调用站", "吊用栈", "调用战"],
        "执行栈": ["执行站", "执行战", "直行栈"],
        "执行上下文": ["执行上下文", "执行上夏文"],
        "词法环境": ["词法环境", "此法环境", "此法还境"],
        "作用域链": ["作用域链", "作于域链", "作用于练"],
        "作用域": ["作用与", "做用语", "左用于", "作于域", "座用于"],
        "词法作用域": ["此法作用域", "此法作用与"],
        "全局作用域": ["全剧作用域", "全菊作用域"],
        "块级作用域": ["块集作用域", "快级作用域"],

        "闭包": [
            "必报", "b包", "闭保", "臂包", "币包", "毕包", "比包",
            "痹包", "臂抱", "必包", "b bao", "b宝",
        ],
        "原型链": [
            "圆形链", "原型练", "圆形练", "原型脸", "圆形脸",
            "远行链", "远行练", "圆形连", "远行连",
        ],
        "原型继承": [
            "圆形记成", "原型记成", "原型集成", "圆形集成",
            "远行继承", "原型计生", "圆形计生", "圆形记承",
        ],
        "构造函数": ["够造函数", "构造函式", "constructor"],
        "实例": ["实力", "事例", "实列"],

        "异步": ["一步", "异部", "已步"],
        "同步": ["同部", "统步", "铜步"],
        "Promise": ["promise", "promise", "普若米斯"],
        "async": ["async", "a sync", "阿信科"],
        "await": ["await", "a wait", "额wait", "额未特", "额喂特"],
        "回调": ["回掉"],
        "回调地狱": ["回掉地狱"],
        "Generator": ["generator", "generate函数", "金瑞特", "生成器", "生成气"],
        "Observable": ["observable", "observe able"],
        "RxJS": ["rxjs", "r x j s", "rx js"],

        "柯里化": ["颗粒化", "科里化", "可理化", "客里化", "颗粒花", "科理化"],
        "高阶函数": ["高街函数", "高接函数", "高洁函数"],
        "高阶组件": ["高街组件", "高接组件", "HOC", "h o c"],
        "纯函数": ["存函数", "唇函数", "春函数", "醇函数", "纯韩束"],
        "副作用": ["副作用", "复制用", "负作用", "富作用", "复左右"],
        "防抖": ["房抖", "反抖", "防斗", "房斗", "凡抖", "debounce"],
        "节流": ["节留", "接流", "截流", "结流", "杰流", "throttle"],
        "深拷贝": ["深考贝", "生拷贝", "深靠背", "深耕贝", "深考背"],
        "浅拷贝": ["前考贝", "钱拷贝", "钱靠背", "浅考贝", "前靠背", "浅靠背"],
        "不可变性": ["不可变形", "immutability"],

        "Proxy": ["proxy", "p r c", "pro x y", "pro xi", "prorxy"],
        "Reflect": ["reflect", "reflex", "瑞flect"],
        "Symbol": ["symbol", "c博", "c播", "c b o"],
        "WeakMap": ["weakmap", "weak map", "we map", "微map", "弱 map"],
        "WeakSet": ["weakset", "weak set", "we set"],
        "迭代器": ["迭代气", "跌代器", "iterator"],
        "Iterable": ["iterable", "可迭代"],

        # ── CSS / 布局 ──
        "CSS": ["css", "C S S", "c s s", "层叠样式表", "层 叠 样式 表", "级联样式表"],
        "HTML": ["html", "H T M L", "h t m l", "超文本标记语言", "超 文本 标记 语言"],
        "DOM": ["dom", "D O M", "d o m", "文档对象模型", "文档 对象 模型"],
        "CSSOM": ["cssom", "css om", "c s s o m", "样式对象模型", "样式 对象 模型"],
        "BOM": ["bom", "B O M", "浏览 器 对象 模型"],
        "Flexbox": ["flexbox", "flex box", "flex博客", "flesh box"],
        "Grid": ["grid", "g r i d", "贵的", "格的"],
        "盒模型": ["和模型", "合模型", "河模型", "box sizing"],
        "BFC": ["bfc", "b f c", "bf c", "B F C"],
        "重绘": ["重会", "重汇", "重回", "重辉", "虫会"],
        "回流": ["回留", "回六", "回刘", "会流"],
        "重排": ["重牌", "虫排"],
        "合成": ["和成", "合层", "和层"],
        "层叠上下文": ["层叠上下文", "曾叠上下文", "stacking context"],
        "响应式": ["响应4", "相应式", "响应是", "相映式", "想应是"],
        "媒体查询": ["媒体查寻", "每体查询", "媒体查讯", "美体查询"],
        "伪类": ["为类", "未类", "危类"],
        "伪元素": ["为元素", "未元素"],
        "选择器优先级": ["选择器优先集", "选择器权重"],
        "z-index": ["z index", "z indexes", "这index"],
        "Sass": ["sass", "s a s s", "S A S S", "萨斯"],
        "SCSS": ["scss", "s c s s"],
        "渲染引擎": ["宣染引擎", "宣染", "绚染", "render engine"],
        "Shadow DOM": ["shadow dom", "沙都dom", "沙多动", "shallow dom"],
        "will-change": ["will change", "willchange"],
        "骨架屏": ["骨架平", "古架屏", "骨架瓶"],
        "首屏": ["手屏", "首页屏幕", "首屏幕"],

        # ── 浏览器 API / 概念 ──
        "JSON": ["json", "J S O N", "杰森", "jason"],
        "AJAX": ["ajax", "A J A X", "阿贾克斯"],
        "API": ["api", "A P I", "诶批挨", "a p i", "诶批i", "诶p i", "a pi"],
        "URL": ["url", "U R L", "u r l", "you are l", "优艾欧"],
        "SPA": ["spa", "S P A", "单页 应用", "s p a", "单页应用"],
        "MPA": ["mpa", "M P A", "多页应用"],
        "PWA": ["pwa", "P W A", "渐进式web应用", "渐进式应用"],
        "Service Worker": ["service worker", "serviceworker"],
        "JSBridge": ["jsbridge", "js bridge", "js桥", "js briage", "js birdge"],
        "WebView": ["webview", "web view"],
        "SVG": ["svg", "S V G", "s v g"],
        "XML": ["xml", "X M L", "x m l", "叉ml"],

        "call/apply/bind": ["call apply bind", "call apply bind"],

        # ── 工程化 / 架构 ──
        "微前端": ["为前端", "未前端", "围前端"],
        "模块联邦": ["模块连邦", "模块联帮", "模块联绑", "module federation"],
        "SSR": ["ssr", "s s r", "服务端宣染", "服务端渲染", "服务 端 渲染"],
        "CSR": ["csr", "c s r", "客户端宣染", "客户端渲染"],
        "SSG": ["ssg", "s s g", "静态站点生成", "静态生成"],
        "Hydration": ["hydration", "水合", "hydrate", "注水"],
        "懒加载": ["懒家在", "蓝加载", "lazy load", "蓝加在"],
        "预加载": ["于加载", "预家在", "preload"],
        "代码分割": ["代码分歌", "code splitting"],
        "Tree Shaking": ["tree shaking", "tree sharking", "去摇树", "树摇", "腰树"],
        "HMR": ["hmr", "h m r", "热模块替换", "模块热替换"],
        "Source Map": ["source map", "sourceMap", "souse map", "源码映射"],

        "diff算法": ["diff算法", "地府算法", "diff 算法"],

        # ── 组件相关 ──
        "组件": ["组建", "component", "康姆剖嫩特"],
        "函数组件": ["函数组件", "function component"],
        "类组件": ["类组件", "class component"],
        "状态": ["装态", "state", "斯得特"],
        "属性": ["属性", "props", "普绕普斯"],
        "生命周期": ["生命周期", "lifecycle", "来夫赛口"],
        "调和": ["调和", "reconciliation", "瑞康斯雷神"],
        "渲染": ["渲染", "render", "瑞恩的"],
        "受控组件": ["受控组件", "controlled component"],
        "非受控组件": ["非受控组件", "uncontrolled component"],
        "状态提升": ["状态提升", "lifting state up"],
        "上下文": ["上下文", "context", "康泰克斯"],
        "Portal": ["portal", "炮特"],
        "React.lazy": ["react lazy", "lazy load", "react点lazy"],

        # ── JS 常用 API ──
        "map": ["迈普", "买普", "m a p", "妈普"],
        "filter": ["飞奥特", "feel特", "f i l t e r", "fi lter"],
        "reduce": ["瑞丢斯", "re duse", "瑞 du 斯", "re duce"],
        "forEach": ["for 一尺", "for each", "佛瑞尺", "for 义齿"],
        "some": ["萨姆", "桑", "s o m e"],
        "every": ["埃文瑞", "爱瑞", "e v e r y"],
        "find": ["放的", "贩的", "f i n d"],
        "findIndex": ["放的 index", "贩的 index", "find index"],
        "includes": ["因克鲁的", "in clues", "in cludes"],
        "push": ["普式", "扑式", "p u s h"],
        "pop": ["炮普", "破普", "p o p"],
        "shift": ["是一福特", "虚福特", "s h i f t"],
        "unshift": ["安是一福特", "安虚福特", "un shift"],
        "splice": ["斯普拉斯", "s p l i c e", "s plice"],
        "slice": ["斯拉斯", "s l i c e", "s lice"],
        "concat": ["康凯特", "con cat", "c o n c a t"],
        "join": ["救因", "j o i n", "joyn"],
        "split": ["斯普利特", "s p l i t", "斯普利"],
        "indexOf": ["index 奥夫", "index of", "index off"],
        "lastIndexOf": ["last index 奥夫", "last index of"],
        "Object.keys": ["object 金斯", "奥布杰克特 keys", "object keys"],
        "Object.values": ["object 外六斯", "奥布杰克特 values", "object values"],
        "Object.entries": ["object 恩垂斯", "奥布杰克特 entries", "object entries"],
        "Object.assign": ["object 阿赛因", "奥布杰克特 assign", "object assign"],
        "toString": ["to string", "to死追应", "two string"],
        "valueOf": ["value of", "外六奥夫"],
        "parseInt": ["parse int", "帕斯int", "parse 因特"],
        "parseFloat": ["parse float", "帕斯float", "parse 福楼特"],
        "isNaN": ["is nan", "is 男", "is n a n"],
        "Number": ["number", "number", "男ber"],
        "String": ["string", "斯追应", "string"],
        "Boolean": ["boolean", "不林", "boolean"],
        "Array": ["array", "阿瑞", "啊ray", "a r r a y"],
        "Object": ["object", "奥布杰克特", "ob ject", "o b j e c t"],
        "Function": ["function", "方格申", "function", "f u n c t i o n"],
        "Date": ["date", "得特", "de特", "d a t e"],
        "RegExp": ["regexp", "regex", "re jex", "瑞杰克斯"],
        "Math": ["math", "马斯", "m a t h"],
        "Error": ["error", "艾弱", "e r r o r"],
        "Set": ["赛特", "s e t"],
        "NaN": ["nan", "男", "n a n", "not a number"],
        "undefined": ["undefined", "安迪范的", "un defined"],
        "null": ["null", "闹", "n u l l", "纳尔"],
        "Infinity": ["infinity", "因飞尼提", "in finity"],

        # ── DOM/BOM API ──
        "document": ["到Q门特", "刀Q门特", "doc门特", "d o c u m e n t"],
        "getElementById": ["get element by id", "给特艾乐门特败艾迪", "getElementByID"],
        "querySelector": ["query selector", "奎瑞selector", "Q selector"],
        "querySelectorAll": ["query selector 奥", "querySelectorAll", "奎瑞 selector all"],
        "createElement": ["create element", "克瑞艾特 element"],
        "appendChild": ["append child", "阿喷的 child"],
        "removeChild": ["remove child", "瑞木夫 child"],
        "innerHTML": ["inner H T M L", "英呢HTML", "inner html"],
        "innerText": ["英呢text", "inner text"],
        "textContent": ["text content", "泰克斯特 content"],
        "classList": ["class list", "克拉斯 list"],
        "addEventListener": ["add event listener", "阿的 event listener"],
        "removeEventListener": ["remove event listener", "瑞木夫 event listener"],
        "阻止冒泡": ["阻止冒泡", "stopPropagation", "斯道普 propagation"],
        "阻止默认": ["阻止默认", "preventDefault", "普瑞问特 default"],
        "window": ["温斗", "win dow", "w i n d o w"],
        "location": ["楼k神", "low k神", "lo cation"],
        "href": ["h ref", "h r e f"],
        "reload": ["瑞楼的", "re load"],
        "history": ["黑斯特瑞", "hi story"],
        "pushState": ["push state", "普式state"],
        "replaceState": ["replace state", "瑞普雷斯state"],
        "navigator": ["乃维给特", "navi gator"],
        "fetch": ["飞吃", "f e t c h", "fatch"],
        "XMLHttpRequest": ["X H R", "x m l http request", "XHR"],
        "axios": ["阿克笑死", "a x i o s", "艾克西欧斯"],
        "请求": ["请秋", "request", "瑞快斯特"],
        "响应": ["想应", "response", "瑞斯胖斯"],
        "状态码": ["状态马", "status code"],
        "请求头": ["请求头", "header", "海德"],
        "请求体": ["请求体", "body", "包地"],
        "GET": ["该特", "get", "给特"],
        "POST": ["抛斯特", "post", "破斯特"],
        "PUT": ["普特", "put"],
        "DELETE": ["地类的", "delete"],
        "PATCH": ["帕吃", "patch"],
        "拦截器": ["拦姐器", "interceptor", "因特塞普特"],
        "超时": ["草时", "timeout", "太亩奥"],
        "重试": ["从试", "retry", "瑞垂"],

        # ── Web API ──
        "EventSource": ["event source", "一问特source", "SSE"],
        "IntersectionObserver": ["intersection observer", "因特塞克神observer"],
        "MutationObserver": ["mutation observer", "谬特神observer"],
        "ResizeObserver": ["resize observer", "瑞赛斯observer"],
        "Performance": ["performance", "普佛曼斯"],
        "Web Worker": ["web worker", "web沃克"],
        "Cache API": ["cache api", "开式api"],
        "推送通知": ["推送通知", "push notification"],

        # ── ES6+ ──
        "解构": ["姐够", "解够", "destructuring", "迪斯特 ra 庆"],
        "展开运算符": ["展开运算符", "spread operator", "斯普瑞的operator"],
        "剩余参数": ["剩余参数", "rest parameter", "瑞斯特 parameter"],
        "模板字符串": ["模板字串", "template literal", "坦普雷特"],
        "可选链": ["可选连", "optional chaining", "奥普申诺 chain 英"],
        "空值合并": ["空值合并", "nullish coalescing", "那累许 扣累森"],
        "BigInt": ["比个int", "big int", "big 英特"],
        "模块": ["摸块", "module", "猫丢欧"],
        "import": ["因炮特", "音炮特", "im port"],
        "export": ["一克斯炮特", "ex炮特", "ex port"],
        "动态导入": ["动态导入", "dynamic import", "带纳米克 import"],
        "for...of": ["for 奥夫", "for 欧夫", "for of"],

        "Docker": ["docker", "doctor", "达克", "dock"],
        "Nginx": ["nginx", "n吉克斯", "engine x", "n jinx", "n金克斯"],
        "Kubernetes": ["kubernetes", "k八s", "k8s"],
        "CI/CD": ["ci cd", "c i c d", "持续集成持续部署", "持续集成"],
        "DevOps": ["devops", "dev ops", "devo ps"],
        "Serverless": ["serverless", "server less"],

        # ── 测试 ──
        "Jest": ["jest", "J E S T", "j e s t"],
        "Cypress": ["cypress", "cy press", "赛pres"],
        "Playwright": ["playwright", "play right"],
        "Vitest": ["vitest", "vi test", "外test"],

        # ── Node.js ──
        "Node.js": ["nodejs", "node js", "Node js", "node点js", "node j s"],
        "Express": ["express", "express框架", "一克斯普瑞斯"],
        "Koa": ["koa", "k o a", "koa框架"],
        "Nest.js": ["nestjs", "nest js", "nest框架"],
        "中间件": ["中间键", "中坚件", "middleware", "middle ware"],
        "Stream": ["stream", "stream流", "流式处理"],
        "Buffer": ["buffer", "缓冲区", "缓存区"],
        "EventEmitter": ["event emitter", "事件触发器", "事件发射器"],
        "PM2": ["pm2", "p m 2"],

        # ── Vue 深度 ──
        "指令": ["指令", "directive", "地瑞克t五"],
        "v-bind": ["v bind", "v 绑的", "v:bind", "冒号"],
        "v-model": ["v model", "v 猫斗"],
        "v-for": ["v for", "v 佛"],
        "v-if": ["v if", "v 衣服"],
        "v-show": ["v show", "v 受"],
        "计算属性": ["计算属性", "computed", "康姆Q特的"],
        "侦听器": ["侦听器", "watcher", "沃车"],
        "生命周期钩子": ["生命周期钩子", "lifecycle hooks"],
        "mounted": ["忙ted", "mount ted", "mounted"],
        "created": ["克瑞艾特ted", "create ted", "created"],
        "组件通信": ["组件通信", "组件传值"],
        "emit": ["一米特", "e m i t"],
        "插槽": ["插槽", "slot", "斯唠特"],
        "混入": ["混入", "mixin", "米克森"],
        "组合式API": ["组合式API", "composition api"],
        "ref": ["瑞夫", "ref", "r e f"],
        "reactive": ["reactive", "瑞艾克t五"],
        "computed": ["computed", "康姆Q特的"],
        "watch": ["watch", "沃吃"],
        "路由": ["路由", "router", "饶特"],
        "状态管理": ["状态管理", "state management", "撞态管理"],

        "语音识别": ["语音识别", "speech recognition", "speech to text"],
        "语音合成": ["语音合成", "speech synthesis", "TTS"],

        # ── 微服务 ──
        "微服务": ["为服务", "未服务", "围服务", "威服务", "味服务"],

        # ── GraphQL / 数据层 ──
        "GraphQL": ["graphql", "graph ql", "g r a p h q l", "格拉夫ql", "g q l"],
        "Apollo": ["apollo", "阿波罗", "a p o l l o"],
        "Relay": ["relay", "瑞雷", "r e l a y"],
        "Prisma": ["prisma", "普瑞斯玛", "p r i s m a", "普瑞斯马"],
        "TanStack": ["tanstack", "tan stack", "坦斯达克"],
        "React Query": ["react query", "react快瑞", "react query"],
        "Zod": ["zod", "z o d", "奏德"],
        "tRPC": ["trpc", "t r p c", "t rpc", "提rpc"],

        # ── CSS 框架 / 方案 ──
        "Tailwind": ["tailwind", "tail wind", "泰尔温的", "t a i l w i n d", "泰文"],
        "Bootstrap": ["bootstrap", "boot strap", "布特斯抓普", "b o o t s t r a p"],
        "CSS Modules": ["css modules", "css模块", "c s s modules", "css module"],
        "Styled Components": ["styled components", "style components", "斯代欧component", "styled component"],
        "Emotion": ["emotion", "一某神", "e m o t i o n"],

        # ── 新兴框架 / 工具 ──
        "Nuxt.js": ["nuxt", "nuxt js", "那克斯", "nux js", "nux t"],
        "SolidJS": ["solidjs", "solid js", "索立德js", "solid"],
        "Astro": ["astro", "a s t r o", "阿是错", "阿斯特罗"],
        "Remix": ["remix", "re mix", "瑞米克斯", "r e m i x"],
        "Qwik": ["qwik", "q w i k", "快克", "quick框架"],

        # ── 运行时 / 桌面 / 移动 ──
        "React Native": ["react native", "react native", "瑞爱的native", "rn", "r n"],
        "Expo": ["expo", "e x p o", "一克斯波", "expo框架"],
        "Electron": ["electron", "e l e c t r o n", "伊莱克创", "electron框架"],
        "Tauri": ["tauri", "t a u r i", "套瑞", "tori"],
        "Bun": ["bun", "b u n", "班", "bun运行时"],
        "Deno": ["deno", "d e n o", "迪诺", "deno运行时"],
        "WASM": ["wasm", "w a s m", "webassembly", "web assembly", "瓦森"],
        "WebAssembly": ["webassembly", "web assembly", "web assemble", "瓦森布利"],

        # ── 测试 / 组件库 / 工具 ──
        "Storybook": ["storybook", "story book", "斯多瑞book", "story布克"],
        "Testing Library": ["testing library", "测试library", "testing lib"],
        "React Testing Library": ["react testing library", "rtl", "react test library"],
        "Chromatic": ["chromatic", "克罗马提克", "c h r o m a t i c"],
        "Radix UI": ["radix ui", "radix", "瑞迪克斯ui", "r a d i x"],
        "Shadcn": ["shadcn", "shad c n", "沙的cn", "shadcn ui"],
        "Headless UI": ["headless ui", "headless", "海德莱斯ui"],
        "Ant Design": ["ant design", "antd", "a n t d", "安特design"],
        "Element UI": ["element ui", "element plus", "element", "爱乐门特ui"],
        "Vant": ["vant", "v a n t", "万特", "vant ui"],
        "Taro": ["taro", "t a r o", "塔罗", "taro框架"],
        "Uni-app": ["uniapp", "uni app", "优尼app", "统一app"],

        # ── 状态管理补充 ──
        "Jotai": ["jotai", "jo tai", "纠太", "j o t a i"],
        "Valtio": ["valtio", "val tio", "沃提欧", "v a l t i o"],
        "XState": ["xstate", "x state", "x state", "x状态机"],

        # ── 包管理 / Monorepo ──
        "Turbopack": ["turbopack", "turbo pack", "特博pack"],
        "Turborepo": ["turborepo", "turbo repo", "特博repo"],
        "Nx": ["nx", "n x", "n叉", "nx工具"],
        "Lerna": ["lerna", "l e r n a", "勒那", "莱那"],
        "pnpm": ["pnpm", "pn pm", "p n p m", "pin pm"],
    },
}
